### ISSUE TITLE
LL 2.0 draft: nodes as 2D array for rect-shaped hex grids

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1001]
@mcflugen I noticed that in the grid-to-graph revision, the grid attribute "nodes" has changed for rect-shaped hex grids. Previously, it was a 2D (rows and cols) array (same as for raster grids); now it's a 1D array. This triggers a problem in the GrainHill model, which assumes a 2D array. Is it feasible to revert to using 2D arrays for rect-shaped hex grids, which have well-defined rows and columns?

**Comment by mcflugen** [comment]
@gregtucker The reason I did this was because an instance of a *HexModelGrid* can have different layouts. While the *rectangular* layout has a clearly defined "shape" of nodes, the *hex* layout doesn't. Because both are just different instances of the same class, I couldn't write a *nodes* method that would work for both and have the same behavior.

Some options:
* define a *nodes* method that checks the node layout and returns either a shaped array or a flattened array, depending on the layout
* no check and always return a flattened array
* define different grid classes for different layouts (i.e *RectangularHexModelGrid*, *HexModelGrid* - or something along those lines). Each class could then have methods that are specific to its layout

I actually kind of like the 3rd option but it's probably too much of a change. I went with the second option because I liked the simplicity and consistency of it - there's no extra check and the method always returns the same thing for that grid type.

The workaround would be,
```python
nodes = grid.nodes # old way
nodes = grid.nodes.reshape(grid.shape) # new way
```
The new way is wordier but is explicit and possibly more clear (?). Anyway, that was my thinking. What do you think?

**Comment by mcflugen** [comment]
@gregtucker A fourth option is to remove the *nodes* method from the grids. It doesn't really do much and is easy enough for the user to generate (`np.arange(grid.number_of_nodes)`) and then reshape however they like.

**Comment by gregtucker** [comment]
@mcflugen actually #4 isn't a bad idea. Saves memory and simplifies. I will go ahead and hack in a solution in GrainHill to deal with the change.

If we implement it, we should deprecate *nodes* and suggest exactly the above as an alternative.

I'll close this issue now.
