### ISSUE TITLE
Confusing flow director error

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1036]
Chatted with @kbarnhart about it. More informative message would be wonderful!
```
 File "C:/Users/pfeif/Documents/GitHub/landlab/landlab/components/network_sediment_transporter/tests/scratch_paper_for_tests.py", line 147, in <module>
    flow_director.run_one_step()

  File "c:\users\pfeif\documents\github\landlab\landlab\components\flow_director\flow_director_steepest.py", line 304, in run_one_step
    self.direct_flow()

  File "c:\users\pfeif\documents\github\landlab\landlab\components\flow_director\flow_director_steepest.py", line 345, in direct_flow
    baselevel_nodes=baselevel_nodes,

  File "c:\users\pfeif\documents\github\landlab\landlab\components\flow_director\flow_direction_DN.py", line 117, in flow_directions
    steepest_slope,

  File "landlab\components\flow_director\cfuncs.pyx", line 15, in landlab.components.flow_director.cfuncs.adjust_flow_receivers

ValueError: Buffer dtype mismatch, expected 'DTYPE_FLOAT_t' but got 'long' ```

**Comment by kbarnhart** [comment]
@pfeiffea thanks for making this issue. 

It occurs because the python underlying the flow direction assumes that `topographic__elevation` is an float, and breaks when it is not. 

What we need to do to address this:
- [ ] Ensure that `topographic__elevation` is a float, and pass a useful error message if it is not. 
    - [ ] On `v2_dev` this can be done as part of the general component init (which means checking both the required and optional inputs). 
    - [ ] On `master` make this change in the `_FlowDirector` component (I think).

**Comment by kbarnhart** [comment]
A follow up on this... It also influences the threshold provided to the stream power components (e.g., if they are provided as an int, a super weird error is raised)

**Comment by mcflugen** [comment]
@kbarnhart I noticed this too when I was running the notebooks. My solution was to add the following to the top of `__init__` for *StreamPowerEroder*,
```python
if not isinstance(threshold_sp, str):
    threshold_sp = np.asarray(threshold_sp, dtype=float)
```

I think I may have also found a bug. I suspect the following line doesn't do what it should when a string is provided for *threshold_sp*.
```python
        if np.any(threshold_sp != 0.0):
```
Since *self._sp_crit* holds numerical values for the threshold, can we just use it instead?
```python
        if np.any(self._sp_crit != 0.0):
```

**Comment by kbarnhart** [comment]
I think you are right that doing

```python
if np.any(self._sp_crit != 0.0):
```
works

However, I don't think what you found is a bug... since a string isn't a zero, then providing a string (e.g., a field name) means that the threshold is set. 

```python
>>> sp = 'wooo'
>>> np.any(sp!=0)
True
```

I, however, am going to focus on (1) our 2.0 beta transition, (2) two papers, (3) then things like this... which is to say that I think this example (and the one @pfeiffea pointed out) are important... but they are bugs that LL users have been dealing with without substantial issue for years...

**Comment by kbarnhart** [comment]
Now that we are on v2, we automagically get a useful error message because I implemented type checking in the component inits:

For example:

```python
from landlab.components.flow_accum import FlowAccumulator
from landlab import RasterModelGrid
import numpy as np

mg = RasterModelGrid((10, 10), xy_spacing=(1, 1))

z = mg.add_field(
    "topographic__elevation", 
    np.random.randint(0, 100, size=mg.size("node"), dtype=int), 
    at="node")

fa = FlowAccumulator(mg)
```
yields the following error message:
```
FieldError: FlowAccumulator optional input variable: topographic__elevation 
at node has incorrect dtype. dtype must be <class 'float'> and is int64
```

So I'm going to close this.
