### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#1046]
Just noticed our little Zenodo DOI badge - and in fact, our automated DOI generation? - is broken. https://zenodo.org/record/154179#.XcWTji10e3I points at Rapunzel, v.1.0.1, and even if you follow the link there to the newest version, it's still only 1.5.4.

We should either get the automation going again (preferred), or take the badge off.

Tagging Eric as person who originally set this up? (sorry Eric)

**Comment by kbarnhart** [comment]
@SiccarPoint its not actually broken. However, in order for the automatic DOI generation to work, the tag must be made by making a release through GitHub rather than tagging locally and pushing to the remote. 

1.5.4 is the most recent version where the tag was done on GitHub.

If you have a thought on how often a new Zenodo DOI should be made... (minor version?) then perhaps that should be discussed here, and we can put into the release notes that those should be tagged on GitHub.

**Comment by kbarnhart** [comment]
@SiccarPoint I think this is resolved. Comment or close?

**Comment by SiccarPoint** [comment]
Yes, I think this has resolved itself.
