### ISSUE TITLE
v2, voronoi, and imshow_grid

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1048]
@mcflugen I'm working on a branch in tutorials to update them to 2.0. When working on `set_BCs_on_voronoi.ipynb` I ran into the following error. I'm pretty sure its because `imshow_grid` hasn't been updated to deal with voronoi post graph2grid...?

<img width="1094" alt="Screen Shot 2019-11-08 at 5 24 41 PM" src="https://user-images.githubusercontent.com/6589339/68519196-ca1eaf00-024c-11ea-855f-25492076cf85.png">

**Comment by mcflugen** [comment]
@kbarnhart Good catch. I think this one might be a little tricky. For this to work, we have to have a *scipy.spatial* representation of the voronoi grid (this is what `grid.vor` was), which is different from how we store the grid in a `VoronoiDelaunayGrid`.

When we first create a `VoronoiDelaunayGrid`, we use *scipy.spatial* to create the needed data structure but we then get rid of it because it doubles the size of the grid and is redundant. We *could* keep it around but it would only be for this use case.

I wonder if `landlab.plot.graph.plot_graph` is an acceptable alternative. If it is, great. If it isn't, perhaps we should change *plot_graph* instead of carrying around the extra data structure.

**Comment by gregtucker** [comment]
I second the idea of not carrying around a heap of extra memory usage if it's not needed. But equally, it would be nice to have *imshow_grid* be grid-type agnostic. What would performance be like if we invoked *scipy.spatial* to create a *vor* data structure only when needed, i.e., when *imshow_grid* is called for a Voronoi?

**Comment by kbarnhart** [comment]
@mcflugen I think that a main benefit of `imshow_grid` is that it is grid-type agnostic. I know I value using it it that way (and probably wouldn't use it as much if it weren't...). Voronoi is less well used, but hex is highly used (e.g., all the CA work)... So I think that something equivalent (and under the same function call) is required. 

I think it is OK to get rid of "show_elements".

This is to say that I don't think that `plot_graph` is an acceptable alternative to `imshow_grid` (unless what you mean to propose is that `imshow_grid` uses `plot_graph` underneath).

If creating the `spicy.spatial` DS is large in memory but fast in wall time, it could be created only when this function is called (but not stored).

If that is not possible, I'd recommend creating a PatchCollection (since pcolormesh only supports quadrilaterals).

**Comment by mcflugen** [comment]
@kbarnhart @gregtucker I guess I'm not totally sure what *imshow_grid* does. *plot_graph* is grid-agnostic but it only plots the topology of our graph data structures. It sounds like *imshow_grid* does that but also plots a field, is that right?

We can convert our data structures back to a *scipy.spatial* data just for this and it might not be too slow but, obviously, it will depend on the size of the grid. This is probably the quickest way forward.

Since *plot_graph* plots topology from our data structures, maybe it wouldn't be too hard to extend its functionality to match what *imshow_grid* does. Something along these lines might work as a longer term solution but  most likely will take longer to implement.

**Comment by kbarnhart** [comment]
@mcflugen in its most common (default) usage, `imshow_grid` plots a field at nodes, spread out over the cells. This is really really really commonly used across raster and hex. 

Once show_elements is dropped, then there are only a few lines that need fixing (and I think fixing using a patch collection will be faster and easier). 

I've started a PR and noted the lines that need to be fixed. 
 
@mcflugen can you take a stab at finishing? I can then test on the tutorials?

**Comment by mcflugen** [comment]
@kbarnhart For sure. Let me know when it's at a point where you would like me to take over.

**Comment by kbarnhart** [comment]
@mcflugen hold on for a moment.

**Comment by kbarnhart** [comment]
@mcflugen if you can take over now. I implemented the skeleton of using patch collection (but haven't quite got it working).
