### ISSUE TITLE
Groundwater component anomalies

### ISSUE THREAD

**Issue by rclavera** [landlab/landlab#1069]
Hi everybody,
I've been tested the groundwater component. First at all, I want to congratulate you for the incredibly good job.
On the other hand, I would like to comment some issues:
I run the next example (code simplified):

[groundwaterExample.py.zip](https://github.com/landlab/landlab/files/3921944/groundwaterExample.py.zip)

1.- In the results we can appreciate an anomaly in the water table (see the attached video ‘water_table.ogv’
[water_table.ogv.zip](https://github.com/landlab/landlab/files/3921922/water_table.ogv.zip)
): it is really strange and I suppose it is a numerical instability.
In other examples with lower thickness (difference between water table and aquifer base)  does not appear
2.- Does the component consider that the seepage only occurs in the line created by water table surface and topographic elevation surface?
![surface_water360](https://user-images.githubusercontent.com/47635648/70145132-b164b600-169f-11ea-9ef7-dd9915427d41.png)
3.- What are the black horizontal lines near the seepage of the previous image?

**Comment by kbarnhart** [comment]
Thanks for the comment and providing the example. I’ve tagged @DavidLitwin , the primary author of the component.

**Comment by DavidLitwin** [comment]
Hi @rclavera, thank you for your contribution to testing this component. I'll do my best to answer your questions here.

1. 
 Just to be clear, the instability feature that you are seeing is this one, correct?
![image](https://user-images.githubusercontent.com/45630470/70253834-36ec7280-1741-11ea-8b77-7e9267f66abf.png)
The figure above shows surface water specific discharge, from the test case that you included. I have seen something like this early in the process of development, but I thought it had been resolved (albeit indirectly, through a variety of changes made for stability). As of right now, I don't have a solution for this, but I would very much like to. If you have any suggestions, I am happy to hear. One thing that I can say is that it does seem to appear when hydraulic gradient is very small (aquifer base is flat, water table is flat or nearly flat). This may provide some insight when looking for a solution. 

2. 
I am interpreting your second question as whether the component only considers seepage at the line of intersection between water table and topographic elevation. To get a better sense of what is going on here, I would look at the equation for surface water seepage:
![image](https://user-images.githubusercontent.com/45630470/70255068-63a18980-1743-11ea-98ed-f9be843acaea.png)

At a given node, there are two conditions that must be met in order to have surface seepage. The first is that the water table elevation must be near the topographic elevation (I say near and not equal to because of the regularization). This is the first part of the equation. The second condition is that the flux into the node must be positive. That is, recharge + divergence of groundwater flow is greater than zero. This is the second term. If both of these are true, seepage is produced at that node.

3.
Is your image here of accumulated surface water discharge? I can't tell exactly what is going on, but I've seen some unusual patterns of accumulated flow when using the `FlowDirectorSteepest` method on synthetic topographies. I would recommend trying D8. 

Again, thanks for your comment. I will see what can be done about issue 2, but I might not get to it for a little while.

**Comment by rclavera** [comment]
Hi @DavidLitwin 
Thank you for assisting me and responding so quickly.

Focusing on point 1:
Exactly, the instability is what you mark in your image 1.
I made some tests and found that it occurs during the computation of the hydraulic gradient, in the function "calc_grad_at_link" (line601).
I mapped the hydraulic gradient:
![grad](https://user-images.githubusercontent.com/47635648/70309484-ee4ebb00-180d-11ea-870f-51af2c770d18.png)

I think this function is defined in landlab/landlab/grid/raster_gradients.py, line 28

**Comment by rclavera** [comment]
Dear @DavidLitwin 

Regarding point 3, I change to 'D8'. That is the result
![shear_stress60](https://user-images.githubusercontent.com/47635648/70316954-1396f580-181d-11ea-99b2-035ca02324f7.png)

much better, but a little strange:

**Comment by DavidLitwin** [comment]
Hi @rclavera,

The instability does seem to appear in the hydraulic gradient, but I wonder whether it starts there, or whether that is what causes it to amplify. 'calc_grad_at_link` is a very simple function - it just returns the difference of node values divided by the link length. If the problem is in one of these basic utilities, it might put it a little out of my area of expertise. @kbarnhart or @mcflugen, any thoughts on this?

As for the accumulated flow, if you want to go one step further, the `MFD` method will surely give a smoother result. As for the occurrence of seepage, one thing I've found very helpful is to visualize the topography and water table in cross section, and see where it is near the surface. Here's a small example:
```
from matplotlib import pyplot as plt
import numpy as np
from landlab import RasterModelGrid

grid = RasterModelGrid((5, 41), spacing=10.0)
elev = grid.add_zeros('node', 'topographic__elevation')
elev[:] = grid.x_of_node/100+2
base = grid.add_zeros('node', 'aquifer_base__elevation')
base[:] = grid.x_of_node/100
wt = grid.add_zeros('node', 'water_table__elevation')
wt[:] = grid.x_of_node/100+1

middle_row = np.where(grid.y_of_node == 30.0)[0][1:-1]
fig,ax = plt.subplots(figsize=(10,5))
ax.fill_between(grid.x_of_node[middle_row],elev[middle_row],base[middle_row],facecolor='sienna' )
ax.fill_between(grid.x_of_node[middle_row],wt[middle_row],base[middle_row],facecolor='royalblue' )
plt.xlabel('Distance (m)')
plt.ylabel('Elevation (m)')
```

Produces:
![image](https://user-images.githubusercontent.com/45630470/70341388-0f181000-1810-11ea-9f23-8ae66f685ddf.png)

**Comment by kbarnhart** [comment]
@DavidLitwin I don't expect there is an issue with `calc_grad_at_link`, but that there is something in the field over which the gradient is plotted. When I've had similar issues, I've looked for the culprit in the variable over which the gradient is calculated (in this case "water_table__elevation", right?)

**Comment by rclavera** [comment]
Hi @DavidLitwin 
I was testing several configurations, changing the aquifer thickness, the courant coefficient, etc... I don't find where is the problem. I'm still looking for.
Thank you.

**Comment by DavidLitwin** [comment]
Hi @rclavera and @kbarnhart,

I've been doing some additional testing and I've come to a few conclusions about what parameter combinations cause the problem to occur, and what a possible solution is. Varying parameters in the code included below it appears that the stability issue appears when: 
- grid spacing is small (maybe < 10m)
- aquifer is thick (maybe > 10m)
- hydraulic gradients are small

It occurs regardless of whether seepage is active or water table is close to the surface. It occurs regardless of Courant coefficient or regularization factor, though it may change form or location. 

I am thinking that instead it is dependent on the upwind scheme that is used to determine aquifer thickness in the groundwater flux equation. The upwind method used is generally considered to be the best combination of simplicity and stability, but it may be that for certain cases, we should use a different scheme, such as a second order upwind scheme. See [these](http://www.bakker.org/dartmouth06/engs150/05-solv.pdf) notes, slide 23-28.

Please let me know what you think!

[gw_stability_test_1.zip](https://github.com/landlab/landlab/files/4042111/gw_stability_test_1.zip)

**Comment by rclavera** [comment]
Hi @DavidLitwin,

I'm agree with you. 
It could be interesting to add as a input parameter the choice of the numerical scheme, according with your attached pdf document. 

Thank you very much.

**Comment by rclavera** [comment]
Hi @DavidLitwin 
I was testing the first example that I sent you, changing the variable _dt_m_ from 86400s to 450s. Then the system is stable.

**Comment by DavidLitwin** [comment]
Hi @rclavera and @kbarnhart, just letting you know I haven't forgotten about this issue, and I think I have a proper solution.

I'll start with the obvious: the Boussinesq equation is a nonlinear advection-diffusion equation. The courant condition only addresses the stability of the advective part of the equation. But the diffusion equation also has a stability criterion, which can be found by von Neumann stability analysis: dt < dx^2/(4*D) for 2D grids. Expanding the equation, the diffusion coefficient is D = khcos(theta)/n. So this might explain why the model encounters stability issues when grid spacing is small and aquifer is thick. This is imperfect because of the nonlinearity and additional terms in the equation, but I think it has much more explanatory power than the courant coefficient alone. 

I have made some changes to the code, which are on branch `dlitwin/gdp_stability`. Both the advective and diffusive time step conditions are calculated and the minimum is chosen. If you have a chance to take a look, I would appreciate it.

**Comment by kbarnhart** [comment]
@DavidLitwin would you mind if I opened a PR for this branch. That way it is easy to see what has changed in the component.

**Comment by DavidLitwin** [comment]
@kbarnhart that sounds good, thank you!

**Comment by kbarnhart** [comment]
@DavidLitwin I think this can be closed. Correct?

**Comment by DavidLitwin** [comment]
Yes, I think so. Thanks!
