### ISSUE TITLE
JOSS paper location

### ISSUE THREAD

**Issue by nathanlyons** [landlab/landlab#1095]
@kbarnhart Currently the directory /landlab/JOSS has a published folder and at the same level, the paper docs for the groundwater component. These docs have the standard joss file names. 

Where should additional papers be placed that are to be submitted? 

Should we instead do directories even for papers in review?

(I understand that the paper.md, etc for a new JOSS submission is added to landlab JOSS directory prior to submitting the paper to JOSS.)

**Comment by kbarnhart** [comment]
@nathanlyons as best as I can tell, the JOSS submission/paper building workflow (the @ whedon bot) gets confused if there are 2 `paper.md` files in the target repository. I say this because I tried to restructure the folders but keep the Lithology paper named `paper.md` when @DavidLitwin was getting ready to submit his paper, but the only way to make it work was to have the Lithology paper get a name that wasn't `paper.md`. Renaming the files isn't at all an issue if only one Landlab component is submitted to JOSS at a time, but I don't know how to approach this if more than one component is under review at the same time. 

I'm going to ask @arfon, the EIC at JOSS what he thinks we should do:

@arfon: We have a question about dealing with multiple in-parallel JOSS submissions in the landlab repository. At the moment there is [one paper](https://github.com/openjournals/joss-reviews/issues/1935) currently under review that provides a Landlab component that deals with the evolution of subsurface groundwater flow (led by @DavidLitwin). @nathanlyons has developed a component that handles species evolution in response to changing topography and he is planning on submitting it (in the very near future, I believe).

This means that we have some issues regarding where to put the two `paper.md` files and keep @ whedon happy.

I structured the repository to have a folder ([`landlab\joss`](https://github.com/landlab/landlab/tree/master/joss)) for joss papers. In it is a folder called 'published' which is where I put a renamed version of the `paper.md` I used in [Barnhart et al., 2018](https://joss.theoj.org/papers/10.21105/joss.00979). At the moment there is one `paper.md` associated with @DavidLitwin 's component. We aren't sure where to put the `paper.md` for @nathanlyons 's component. 

If this question is better asked over in the [joss repo](https://github.com/openjournals/joss/issues), LMK and one of us will re-ask it there. 

_Note on Landlab terminology/design: In Landlab a "component" is a python class that represents an Earth surface physical process through a standard interface.  By providing a core model domain representation and this interface standard, the Landlab project is trying to support our community in creating re-usable and interoperable numerical models._

**Comment by arfon** [comment]
Hrm, yes, I'm afraid this does break our workflow with Whedon unfortunately. Whedon basically looks for anything named `paper.md` in the repository. When working locally, Whedon can ask which paper it should compile but for the GitHub/bot environment it just picks the first one.

One possibility might be to have two different branches for each of the submissions? Whedon can handle compiling papers from different branches already. Might that work?

**Comment by nathanlyons** [comment]
@arfon, different branches may work. Is all that needs to be done, on the 'Submit software for review' page is include the branch repo address in the 'Repository address' field?

@kbarnhart, would this general workflow work?
- internal landlab review
- merge new feature branch with master
- new branch for JOSS review
- submit software/paper for review to JOSS
- once JOSS review has completed and if paper is accepted:
    - rename paper.md to something else, place it in `/landlab/JOSS/published/<name>/` or even just `/landlab/JOSS/<name>/` because all there will be on master is published papers
    - PR: JOSS review branch > landlab master

In this case, in my JOSS review branch, I will need to replace the groundwater paper.md with my paper.md.

**Comment by arfon** [comment]
> @arfon, different branches may work. Is all that needs to be done, on the 'Submit software for review' page is include the branch repo address in the 'Repository address' field?

Actually you can't specify this in the submission form - Whedon wants a bare HTTP repository address (e.g. https://github.com/landlab/landlab) to clone from but in the review you can do things like `@whedon prepare pdf from branch my-custom-branch-name`

**Comment by nathanlyons** [comment]
I see. Thanks, @arfon.

**Comment by kbarnhart** [comment]
@arfon thanks for the recommendations:

@nathanlyons I think this would work. Slight modifications below:

- internal landlab review for contribution. 
- merge new feature branch with master
- new branch for JOSS paper only, places paper at 
`landlab/joss/<name_of_module_or_component >/paper.md`
- submit software/paper for review to JOSS, indicating in the notes that the paper is on a branch.
    - submitting author should make sure to comment on the pre-review issue that the paper is on a branch, and they should build from the branch as @arfon indicated 
 ```
@whedon prepare pdf from branch my-custom-branch-name
```
- once JOSS review has completed and if paper is accepted, merge paper PR so that the archived version of the code uses the `master` branch and includes the `paper.md`. 
- assuming publication, after publication is completed, make another PR to move and rename the `paper.md` to `landlab/joss/published/<name_of_module_or_component>/something_else.md`

In the short term, I think this means that we need to remove @DavidLitwin's `paper.md` and `.bib` from the master branch, place it on another branch, and indicate as such in his Review issue. I'm going to let @DavidLitwin do this.

Once that happens, I think @nathanlyons will be all set to proceed.

tagging @margauxmouchene @pfeiffea and @SiccarPoint as I believe they will find this information useful at some point.

**Comment by nathanlyons** [comment]
Thanks @kbarnhart. Modified workflow makes sense to me.

Is there a moment late in the review process where the link to the component/module readme can be updated? During review, I think it makes sense to have the paper's readme link point to the JOSS branch readme, otherwise reviewers may get confused looking at the repo. If there is a time to change the readme link, should it be changed to the master branch , permanently in the publication?

**Comment by arfon** [comment]
@kbarnhart one slight suggestion as it's not entirely explicit from your described workflow:

> - once JOSS review has completed and if paper is accepted, merge paper PR so that the archived version of the code uses the master branch and includes the paper.md.

Actually to *publish* the JOSS paper, it would be ideal if you could merge the paper PR. So 1) JOSS accepts 2) Paper is merged into `landlab/landlab` `master` 3) JOSS publishes.

This will make sure that all of the links work reliably once the paper is accepted.

**Comment by nathanlyons** [comment]
Following @afon's comment, @kbarnhart is it ideal and tenable that paper.md links (1) point to review branch while in JOSS review and (2) point to release branch once published? Meaning a release would happen between JOSS paper acceptance and publication.

**Comment by kbarnhart** [comment]
@arfon thanks for the clarification. The steps you wrote were what I was thinking, but I didn't make it clear. I've revised this again. I think I have it right.  

@nathanlyons, might you make a PR to put this in the docs?

- internal landlab review for contribution. 
- merge new feature branch with master
- new branch for JOSS paper only, places paper at 
`landlab/joss/<name_of_module_or_component >/paper.md`
- submit software/paper for review to JOSS, indicating in the notes that the paper is on a branch.
    - submitting author should make sure to comment on the pre-review issue that the paper is on a branch, and they should build from the branch as @arfon indicated 
 ```
@whedon prepare pdf from branch my-custom-branch-name
```
- once JOSS review has completed and if paper is accepted:
    - merge paper PR into `master` branch
    - merge `master` into `release`, and update version number.
    - ensure that the release is correctly created and distributed. 
    - update JOSS Review PR with correct archive DOI and version number. 
- JOSS publishes paper
- After publication is completed, make another PR to move and rename the `paper.md` to `landlab/joss/published/<name_of_module_or_component>/something_else.md`

**Comment by nathanlyons** [comment]
I'm on it!

**Comment by nathanlyons** [comment]
@DavidLitwin & @kbarnhart I may submit to JOSS tomorrow, Weds. I think it'll be ok with the groundwater paper named 'paper.md' on master because I will ask Wheldon to build from a different branch where I'll remove the groundwater paper.md.

**Comment by kbarnhart** [comment]
sounds good @nathanlyons. Let me know if you need anything else from me as you submit.

**Comment by nathanlyons** [comment]
@DavidLitwin may you please rename the groundwater paper.md as described in the last step [here](https://landlab.readthedocs.io/en/master/development/contribution/joss_workflow.html#workflow-to-submit-your-landlab-contribution-to-journal-of-open-source-software)?

It just so happened that my paper's review is finishing up shorting after your's concluded, and we are new to working out how to handle concurrent JOSS submissions.

**Comment by DavidLitwin** [comment]
@nathanlyons got it, I just added those changes to my post-joss pull request #1150
