### ISSUE TITLE
Unclear which components require specific units

### ISSUE THREAD

**Issue by vaga3461** [landlab/landlab#1104]
I've created a grid and specified that I want topographic elevation to be in kilometers, and now I'm using FastscapeEroder on that grid. "FastscapeEroder.units" says that FastscapeEroder elevations are in meters. It's unclear to me if I can use this component on a grid with different units.

**Comment by nicgaspar** [comment]
Landlab does not explicitly handle units. So you can have elevation in your units of choice, just make sure that you are being careful about unit conversion. That is, drainage area also has units, and those units are dependent on the units of dx and dy.

**Comment by kbarnhart** [comment]
@vaga3461 and I discussed this a bit and based on that conversation I have some additional thoughts:

At present almost all components are unit agnostic (OverlandFlow, KinwaveImplicitOverlandFlow are two I can think of that are not, I know there are others). However, we indicate (for fields and input parameters), units instead of dimensions. 

We have discussed presenting dimensions instead of units. However, each time this has come up (I have been present for two versions of this conversation and know that more occurred before I joined the dev team), we end up deciding that the default values themselves have units, and thus we should use those units instead of dimensions. 

However, unless a user digs into the source code to determine whether a component truly is unit agnostic or not, it is not clear which landlab components are unit agnostic and which ones are not. 

I would propose that we consider adding a piece of metadata to components which indicates:

a. I am unit agnostic, just be consistent with your units and you'll be fine. 
b. I do actually care about my units and you must look at my units carefully to use me correctly. 

What do others think. 

Ultimately, I'm open to any solution which makes unit agnostic/not agnostic clearer to a user. 

:wave: @landlab/core

**Comment by gregtucker** [comment]
I agree a unit required/agnostic indicator would be a useful addition to component metadata. Perhaps an optional header item: `_unit_agnostic = True`

**Comment by kbarnhart** [comment]
On the call we've decided that it makes sense to 

* Add a `_unit_agnostic = True` to component base class, then add `_unit_agnostic = False` to those components for which it really matters. 
* Add public attribute to Component. Add information to info printed about component
* Add information to the Component tutorial. 

@landlab/core anyone want to volunteer to do this.
