### ISSUE TITLE
Landslide component driven by soil water leakage from soil moisture component?

### ISSUE THREAD

**Issue by ChristianMohr** [landlab/landlab#1121]
Hello there,
I am relatively new to landlab, did some tutorials and managed to develop a landslide model accounting for dynamic root cohesion over time following disturbance.
Now I am planning to link the soil moisture component to the landslide component. My idea is to use the "soil_moisture__root_zone_leakage" output as recharge as required for the landslide component to run. I saw the different docs and tutorials for the landslide component and it seems like you can use "data driven spatial" recharge. Following the tutorials, spatially distributed recharge is possible for VIC outputs:

_"Load pre-processed routed flows dictionaries containing HSD_id and fractional drainage at each node and recharge dictionaries. HSD is the Hydrologic Source Domain, which is the VIC data in this case study at ~5x6 km2 grid size. The 'pickle' utility loads existing dictionaries."_

I now need to get the leakage from root zone in the following format:

_dict of node id (key) and HSD_ids (values)_
HSD_id_dict = pickle.load(open(data_folder+'/dict_uniq_ids.p', 'rb'))

_dict of node id (key) and fractions (values)_
fract_dict = pickle.load(open(data_folder+'/dict_coeff.p', 'rb'))

_dict of HSD id (key) with arrays of recharge (values)_
HSD_dict = pickle.load(open(data_folder+'/HSD_dict.p', 'rb'))

In order to merge them:
HSD_inputs = [HSD_dict,HSD_id_dict, fract_dict]

I'd be glad if anyone that might have an idea how to solve this could respond to my issue.
Thanks in advance
Best,
Christian

**Comment by erkanistan** [comment]
Hi Christian, 

I think for this you will need to run the soil moisture model for a long duration and select the wettest day of each year to force the landslide model. if you have let's say 30 years of daily soil moisture run then you will have 30 landlab recharge grid at the resolution of your choice. the landslide model requires a steady-state recharge at each you calculate landslide probability, and this requires the spatially averaged recharge represented at the cell where the probability calculated so that Rw can calculated. The STA utility is used to get that recharge (see page 54, first para, Strauch et al., 2018). 

If you have a small watershed and you use spatially constant rainfall the maximum recharge of each year may actually not vary spatially. Unless you have orographic precip, Temperature dependent rain/snow partitioning and snowmelt model you may want to first explore the soil moisture model and make maps of recharge. in the case of a fairly homogenous recharge, which I suspect would be the case when rainfall is ample, then the resulting maximum recharge time series can be just used as input for a spatially uniform pdf. 

BUT if you see the need to route the recharge using STA then you will need to use the maximum recharge raster for each year from soil moisture as HSD (hydrologic source domain) and run STA (source tracking algorithm) which will give you the spatially-averaged recharge map for each year (see page 53 left column of Strauch et al., 2018).  with that you can use the data_driven_spatial option for recharge input.

Hope this helps, please let us know how it goes.

**Comment by ChristianMohr** [comment]
Thanks Erkan, I'll keep you in the loop.
Best,
Christian

**Comment by ChristianMohr** [comment]
Sorry, it is me again. I think the STA makes sense in my case, at least it is worth trying. Th study area is pretty heterogeneous in terms of topography (Patagonian Andes).

I checked the docs you referred to, Erkan, and also searched the manual on the landslide component which describes how the VIC data is routed, as well as the manuals of the STA. Yet, it seems like I somehow need to provide the "hsd_ids" for the STA. I am not sure how I can get them from the modeled root leakage data. Anybody with any idea?

**Comment by erkanistan** [comment]
hsd_id could be anything you want. Then you have the look up table that pairs the hsd_id to the landlab cell ids. So the recharge array for the hsd_id then gets linked to the landlab id via python dictionaries. if you use landlab for recharge then hsd_id can be rater model grid id. BUT there is a need for flow direction for STA-- please see: https://landlab.readthedocs.io/en/latest/reference/utils/source_tracking_algorithm.html

erkan

**Comment by ChristianMohr** [comment]
Hi Erkan,
thanks, this makes sense. It does, thus, not make any difference how to 
assign he hsd_id since they are unambiguously assigned.

I have the flow direction data calculated.
I think, I now, what you meant when stating you like to work late. I really 
enjoy working tonight.... no baby, no kid and wife who needs to be taken 
care of ;-)
Christian


On Wed, 22 Jan 2020 21:28:00 -0800
  Erkan Istanbulluoglu <notifications@github.com> wrote:
> hsd_id could be anything you want. Then you have the look up table 
>that pairs the hsd_id to the landlab cell ids. So the recharge array 
>for the hsd_id then gets linked to the landlab id via python 
>dictionaries. if you use landlab for recharge then hsd_id can be 
>rater model grid id. BUT there is a need for flow direction for STA-- 
>please see: 
>https://landlab.readthedocs.io/en/latest/reference/utils/source_tracking_algorithm.html
> 
> erkan
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/landlab/landlab/issues/1121#issuecomment-577511499

---
Dr. Christian Mohr
University of Potsdam
Institute of Environmental Science & Geography
Geohazards Research Group
Karl-Liebknecht-Strasse 24-25
D-14476 Potsdam
Golm, Complex II, House 27, Room 0.26
Tel. (+49)331 977 5875

**Comment by kbarnhart** [comment]
@ChristianMohr is this issue resolved? If so is it OK to close the issue?

**Comment by gregtucker** [comment]
It looks as if this has been resolved, so I'm closing it.
