### ISSUE TITLE
Difficulties in applying the Layers component

### ISSUE THREAD

**Issue by rclavera** [landlab/landlab#1141]
Dear Landlab team,
I really appreciate your work and efforts.
I'm making my LEM using several of your components.
Trying to include layers I had some problems. I probably did something wrong but I don't know what.
Running the attached example, the model applies just 1 layer and when I print a cross-section it does strange things (it works with other data like groundwater)
I attached files to run the sample.
[Archive.zip](https://github.com/landlab/landlab/files/4152455/Archive.zip)

**Comment by kbarnhart** [comment]
@rclavera a few thoughts and clarification questions. 

- Could you describe in a bit more detail what you are trying to model and how you are intending to use the LithoLayers component? It is not entirely clear to me from the example you provided. As such it is hard to know whether what you want to do is possible under the current capabilities of Landlab. 

- If your goal is to define layered rock with layers of variable hydraulic conductivity and run the GroundwaterDupuitPercolator on it, I sadly must inform you that this likely will not work. The LithoLayers and Lithology components were designed to represent subsurface characteristics, and to update a field representing what is present at the surface. They were not designed to integrate with a component such as the GroundwaterDupuitPercolator. The following is a notebook showing some examples of using the LithoLayers component:
https://mybinder.org/v2/gh/landlab/landlab/release?filepath=notebooks/tutorials/lithology/lithology_and_litholayers.ipynb

- A small code observation: one reason that your first cross section plot doesn't make sense is that in the line

```python
ax.fill_between(
    mg.y_of_node[middle_row], 
    z[middle_row], 
    mg.at_node['rock_type__id' ][middle_row]
    )
``` 
you use `mg.at_node['rock_type__id']` for the fill_between keyword argument `y2`. I suspect you mean to use the elevation of the bottom of layer one rather than the rock type id.

**Comment by rclavera** [comment]
@kbarnhart 
I would like to simulate several horizontal layers with different diffusion coefficients crossing the surface of a slope to erode them by diffusion (nothing to do with groundwater). 

I tried to follow the notebook, but the result was the one you already saw. I guess I don't get it.

**Comment by kbarnhart** [comment]
@rclavera it sounds like you want to couple the LithoLayers with the LinearDiffuser. Is that correct? I would recommend that you revisit the example notebook and pay particular attention to part 3 where I show an example of coupling these two components (along with a few other components).

**Comment by rclavera** [comment]
@kbarnhart 
Solved
Thank you

**Comment by kbarnhart** [comment]
Glad to hear you solved this. Closing.
