### ISSUE TITLE
Problems with run_one_step() input for Lithology Tutorial

### ISSUE THREAD

**Issue by mckeonryan406** [landlab/landlab#1164]
I am trying to learn how to use the Lithology and Litholayers components of LandLab and I am running into issues with the run_one_step() function as implemented in input [9] and input [11] in the Tutorial  from here: https://nbviewer.jupyter.org/github/landlab/tutorials/blob/release/lithology/lithology_and_litholayers.ipynb

If I follow all of the preceding steps in the example and execute the following from In [9]:
z -= 1.
dz_ad = 0.
lith.run_one_step(dz_advection=dz_ad)

I get:  TypeError: run_one_step() got an unexpected keyword argument 'dz_advection'

After looking at the source code on the Readthedocs site, I tried changing to this:
z -= 1.
dz_ad = 0.
lith.run_one_step()

Which runs successfully and produces a result that makes sense (i.e. plotting the surface before and after executing the run_one_step() function illustrates the expected change in plan view given the strike and dip of the rock layers).

I am curious what I am doing wrong...  full disclosure... I am brand new to LandLab and so I apologize if my question is very remedial in nature.

Many thanks for the great tools and documentation.

**Comment by kbarnhart** [comment]
@mckeonryan406 thanks for the question. 

As of Jan 2020 landlab switched from v1.x to v2beta (in beta until [a publication presently at ESURF](https://www.earth-surf-dynam-discuss.net/esurf-2020-12/#discussion) is reviewed, etc).

As part of the major revision resulting in v2.0, we decided that run_one_step methods would either take dt or nothing (e.g., no more passing dz_advection to run_one_step). 

The tutorials repo (https://github.com/landlab/tutorials) that nbviewer was pointing at is no longer being maintained and out of date. Now all tutorials are located in the main landlab repository (https://github.com/landlab/landlab) in a folder called "notebooks". I would recommend that you look there for the most up to date version of notebooks. 

I hope that this answers your question. If not, please let me know how to clarify and either myself or someone else will do so. 

In addition, it would be very helpful to me if you pointed me towards where you found the link you used: https://nbviewer.jupyter.org/github/landlab/tutorials/blob/release/lithology/lithology_and_litholayers.ipynb

We are trying to update all the docs and public facing parts of landlab so that new users are steered towards the v2beta version of everything, but there are a lot of things to fix.

**Comment by mckeonryan406** [comment]
Many thanks for the quick response!  I will talk with my thesis student to find out where they found the link I gave you to the out-of-date tutorial, but my guess is that it was something that Google lead them too so I am not sure if they will be able to get too specific (sorry in advance).

Thanks again for the fast reply and the great tools and documentation (now that I know where to look)!

**Comment by kbarnhart** [comment]
@mckeonryan406 I'm going to close this issue since I think I've resolved your questions. If you or any of your students have questions about Landlab, please don't hesitate to make a new issue.
