### ISSUE TITLE
Tutorial interface very user-hostile in updated website

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#1169]
Just noticed that in the process of cleaning up the tutorial section of the website, we've largely wiped all the useful information on what the tutorials do, what order to do them in, etc. This seems essential for a novice user, especially one out on their own in the wild.

(Possibly this is still in there somewhere, but you don't see it if you do the obvious route of Splashpage -> "Tutorials" -> "Notebooks".)

This probably needs restoring.

**Comment by SiccarPoint** [comment]
Lots of broken links in here as well. Will fix the ones I find.

NB: We appear to have deleted the diffusion_three_ways notebook tutorial from the repo entirely. I am taking it out of the docs altogether, but if @gregtucker or @kbarnhart feels this is in error, we'll need to put it back later.

**Comment by SiccarPoint** [comment]
Wait, reading between the lines, diffusion 3 ways is now the scarp diffusion model - going with that.

**Comment by SiccarPoint** [comment]
Hang about, @kbarnhart has already made quite a lot of changes ([here](https://github.com/landlab/landlab/commit/60c52c546d47e2dd4f5abb744a795cdef4f197fd#diff-124d0f2ef03bc55af34f89e4e02bb362)), but this hasn't been pushed to the user-facing website. Is there some procedure I've missed to rebuild the docs that needs to be triggered manually? I note these changes aren't visible even in the "Master" doc version, which surely they should be?

Nonetheless, still going to tweak a bit and fix some dead links.

**Comment by kbarnhart** [comment]
@SiccarPoint thanks!

A couple of comments:

1) Doc builds are currently failing on ReadTheDocs (and have been for a while). This is why @nathanlyons's improvements aren't showing up. If someone else has the bandwidth to assess/fix, please do... Error is very early on in the build. 
```
conda env create --quiet --name latest --file docs/environment.yml
Collecting package metadata (repodata.json): ...working... Killed
Command killed due to excessive memory consumption
```

2) You are right that in the big re-org the page on the docs that listed tutorial order was removed and replaced with a jupyter notebook that provides a "welcome page" (and also a "syllabus"). I started by having both the old .rst page and the new jupyter page. I realized that maintaining the both (when they have the same info) was going to be a pain (esp. b/c of rst <-> md conversion), and so I went with the jupyter version because its relative links mean that it will work on binder/locally/etc. 

3) There are other tutorial loose ends. I did my best to compile them on #1080

4) @SiccarPoint when you say "website" could you clarify whether you are referring to the GitHub.io page or the readthedocs page. I 100% agree with you that Splashpage -> "Tutorials"  should take you to a good place. Know, however, that in my revisions I've worked to consolidate the actual content on read the docs (not because I particularly love read the docs but because we previously had three places to put info (splash, rtfd, and GitHub wiki) and my experience was that we should have the information in ONE place. Of those three, RTFD was identified as the best (and we can do things like link checking with it), so I went that way.

**Comment by SiccarPoint** [comment]
The page that triggered the issue was the [RTFD tutorials page](https://landlab.readthedocs.io/en/latest/user_guide/tutorials.html), where I subsequently discovered your changes. I think the flow from the splash page will actually be fine once these updates appear...?

I think I remember the RTFD consolidation discussion, and am still very much on board. The main issue is signposting now I think - i.e., if you click on "tutorials", you should be able to tell that this isn't the only place you can get training resources from, and also be pointed more clearly at the actual contents/welcome page. What is a tutorial, even? I hope I got a bit of this as part of this PR - but as I say, the changes I discovered you already made massively help.

I'll see if I can figure out that error if I get a bit of time, just to have another pair of eyes on it. But maybe don't hold your breath. Is there an issue for it?

The Binder functionality is awesome BTW.

**Comment by gregtucker** [comment]
@siccarpoint also know that we've had an active discussion in Landlab meetings on managing the distribution of notebooks. Current temporary solution is to recommend users clone the repo just to get access to the .ipynb files. Longer-term solution will be to host the notebook files on a server for downloading them without having to clone the full LL repo.
