### ISSUE TITLE
Erosion of flooded nodes in space

### ISSUE THREAD

**Issue by BCampforts** [landlab/landlab#1172]
Hello, 

I might be overlooking something but from what I see, I have the impression that flooded nodes are still eroded in the space.py component even when the erode_flooded_nodes flag is set to False and when using the run_one_step_basic definition. There seems to be a fix for this in the run_with_adaptive_time_step_solver definition on lines 625-627 but this does not apply for the solver with a fixed time step. A solution would be to remove the 625-627 lines and add them in the _calc_erosion_rates definition by passing 'flooded_nodes' as an argument and setting 
self._sed_erosion_term[flooded_nodes] = 0.0
self._br_erosion_term[flooded_nodes] = 0.0

**Comment by gregtucker** [comment]
Vanessa and I unearthed a related issue in ErosionDeposition: nodes that are either flagged "flooded" by a lake/depression identifier, or are self-draining, *should* have a deposition rate equivalent to the incoming sediment flux, but do not. I hope to look at this and the above SPACE issue in the next day and a half.

**Comment by BCampforts** [comment]
Regarding deposition in space.py: Charlie also noticed there should probably be a += on line  469 rather than an =

**Comment by kbarnhart** [comment]
@gregtucker if I recall correctly you @cmshobe and I had a couple of conversations about what should happen when water enters a flooded node. If memory serves, we considered:
a) sediment is deposited at a rate of dHdt (some sediment is deposited some is passed downstream) and
b) all sediment is deposited. 

I think you favored (b), @cmshobe favored (a), and I wasn't certain which made more sense. 

I *think* what you are indicating is that it should be (b), right?

Whatever the case, I think that we should do the same thing to SPACE and ErosionDeposition. 
 
@BCampforts based on a brief assessment I think your diagnosis and approach are correct.

**Comment by gregtucker** [comment]
@kbarnhart yes, that's right. This was prompted by a simple experiment that Vanessa ran: a 5x5 domain with all closed boundaries, cells in one row at an arbitrarily high elevation, the rest at zero. Mass should be conserved within the domain, but isn't if you use (a) above because there is currently no mechanism to pass sediment downstream if there is no downstream defined.

**Comment by cmshobe** [comment]
Ohhh ok this is coming back now. I had forgotten about the flow routing part (i.e. lakes being their own receiver). Couple of thoughts:

1) Mass should be conserved, I agree. However, I wonder if in approach (b) you might deposit too much and basically make a little mountain? Not saying this has to get done now, but wouldn't the best long-term solution be (a) but with the change that those internally drained nodes can somehow pass the rest of their qs downstream? Like in some of the fill&spill things @BCampforts is looking into? Otherwise, totally on board with moving to approach (b) for the sake of mass conservation.

But 100% agree with Benjamin's initial point, which is that erosion needs to be suppressed in flooded nodes.

**Comment by kbarnhart** [comment]
@gregtucker Ahhh. The context of @vaga3461 's experiment helps me understand. 

Also, sorry to @BCampforts since this second issue (which probably belongs on another thread) is now taking over.  

Right now we (in theory) have my option (a). Putting aside whether (a) or (b) is better, @vaga3461 's example demonstrates that we have an imperfect version of (a). Specifically, if there are local minima, (e.g., no depression finding done), then a dH/dt*dt thickness of sediment is deposited at the sink and the rest of the sediment evaporates. This would be reasonable at open boundaries, but not at closed boundaries or sinks.

**Comment by kbarnhart** [comment]
I'm going to create a separate issue to describe @vaga3461 's issue, since her issue and @BCampforts are distinct. 

Based on discussions with @gregtucker and @vaga3461 yesterday we thought that it would be best to try and resolve the second issue once this issue was resolved.
