### ISSUE TITLE
Using Landlab to model wind erosion? 

### ISSUE THREAD

**Issue by braunchris** [landlab/landlab#1174]
Hello, 

I am very new to Landlab and was wondering if it could be used to model wind erosion. Could it be done and has it been done already?

If not, why? 

Your help would be greatly appreciated!

Best regards,
Chris

**Comment by gregtucker** [comment]
Hi Chris,

I believe that Harrison Gray at the USGS has recently done some wind erosion/transport/deposition modeling, using a combination of Landlab code that he wrote for sediment transport plus a 3rd-party wind model. So that shows that Landlab *can* be used to model wind erosion, but we don't currently have a pre-existing component to do this.

Regards,
Greg
