### ISSUE TITLE
xarray issue in release (v.2.1.1)

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1206]
Using the latest release, and I'm having problems with read_netcdf, apparently because of xarray. Attached is a minimum reproducible example (script and nc file), and here is the traceback:
```
Traceback (most recent call last):

  File "C:\Users\dgbli\Google Drive\Research\Landscape evolution\Landlab_runoff_LEM\Tests\xarray_problem\xarray_problem.py", line 11, in <module>
    grid = read_netcdf('grid.nc')

  File "c:\users\dgbli\landlab\landlab\io\netcdf\read.py", line 405, in read_netcdf
    grid.add_field(name, values, at="node", clobber=True)

  File "c:\users\dgbli\landlab\landlab\field\graph_field.py", line 1061, in add_field
    ds.set_value(name, value_array, attrs=attrs)

  File "c:\users\dgbli\landlab\landlab\field\graph_field.py", line 295, in set_value
    self._ds = self._ds.drop_vars(name)

  File "C:\Users\dgbli\Anaconda3\envs\landlab_dev\lib\site-packages\xarray\core\common.py", line 183, in __getattr__
    (type(self).__name__, name))

AttributeError: 'Dataset' object has no attribute 'drop_vars'
```
After pulling the latest release I ran landlab `setup.py develop` again, and didn't notice any significant errors. Python version is 3.7.3, xarray version is 0.12.3, netCDF4 version is 1.5.1.2. Any ideas on what might be causing this?

Thanks!

[xarray_problem.zip](https://github.com/landlab/landlab/files/4668973/xarray_problem.zip)

**Comment by kbarnhart** [comment]
you need to update your xarray.

**Comment by DavidLitwin** [comment]
A simple update didn't do it, but I just rebuild the landlab_dev environment, and I'm all set. Glad it wasn't too bad.

**Comment by kbarnhart** [comment]
Odd. Not entirely sure why conda update wouldn't just get the newest xarray and solve the issue.... 

Either way @mcflugen we probably need to specify a minimum version for xarray. I'm going leave this issue open to motivate that. I think the minimum version we need is v0.14.1 since that is when this function was added. 

http://xarray.pydata.org/en/stable/whats-new.html?highlight=drop_vars#v0-14-1-19-nov-2019

Also, this is the same issue as #1201
