### ISSUE TITLE
'on_diagonals' diffusion missing grid attribute

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1236]
I'm experimenting with the diffusion to all adjacent cells in landlab, and I've run into an issue. 

Instantiating LinearDiffuser with method 'on_diagonals' is possible but calling `run_one_step` gives `AttributeError: 'RasterModelGrid' object has no attribute _diag_activelink_tonode`. 

I searched in the whole code repository, and line 552 in diffusion.py appears to be the only place where this attribute exists. This seems to be similar for `_diag_activelink_fromnode` too. Maybe these were orphaned somewhere in the LL2.0 process? I would be interested in helping if there is a simple fix. 

Furthermore, there are no component tests for methods other than 'simple'. Seems like this would be useful.

Here is an example:
```
from landlab import RasterModelGrid
from landlab.components import LinearDiffuser

grid = RasterModelGrid((10, 10), xy_spacing=10)
z = grid.add_ones('node', 'topographic__elevation')

ld = LinearDiffuser(grid, 0.001, method='on_diagonals')
ld.run_one_step(1)
```

**Comment by SiccarPoint** [comment]
Hi David - these were experimental methods from some time ago now. You're right, they've been decapitated in the grid cleaning at 2.0. The supporting methods have been cleaned away, because there were no tests. They probably should have been cleaned out at the same time. You might need reinstate them yourself if you want them...

**Comment by DavidLitwin** [comment]
Hi Dan, thanks for the info. Did you get them working satisfactorily in pre-2.0 versions? I'm not sure my need is strong enough to reinstate them at the moment. Maybe best would be to remove them for the sake of reducing confusion, but keep them on a branch that someone could work on later. 

My current issue is related to using D8 for incision and 'simple' (D4) for diffusion. Seems to be producing some artifacts in my results. I'm suspecting I will move to a voronoi mesh or something before I go all out on making diffusion on diagonals for a raster grid.

**Comment by SiccarPoint** [comment]
Yes, I too was struggling with conflict between D8 flow and D4 diffusion. Do feel free just to remove it. Can always reinstate later. I was never totally happy that the scheme I had going for this was justified, and couldn't justify sinking any more time into it after a certain point. This was long enough ago that our modern QC processes weren't in place!

**Comment by DavidLitwin** [comment]
Sounds good. Did you come to any other resolution on the D8 routing vs D4 diffusion issue? I'll work on removing sometime soon when I get the chance.

**Comment by gregtucker** [comment]
For what it's worth, IIRC Beaumont et al. 1992 reported using a D8-style diffusion algorithm in their early landscape model. I think the conceptual problem is that there is no contact between cell faces diagonally, and hence should not be any direct flux between them (though of course it happens indirectly via the in-between cells). I suppose that's also an argument against D8 flow routing, but that's a bit different because it's a quasi-1D network rather than a true 2D flow field. @DavidLitwin have you tried running your model on a hex grid? That would be one way to resolve the dilemma.

**Comment by DavidLitwin** [comment]
Interesting, I hadn't really thought about the quasi-1D network aspect of flow routing. I remember trying the hex grid early on for my full groundwater landscape evolution model, but found that running the groundwater model on a hex grid was quite slow because of the additional links. That's the cost I suppose! Something to consider down the road potentially.

**Comment by gregtucker** [comment]
I'm surprised to hear that you got slower performance with hex. In principle, you do have ~50% more links in a hex grid (not counting diagonals), but that shouldn't be a huge hit. One area where hex grids are notably slower is in `imshow_grid` plotting.
