### ISSUE TITLE
landlab Lithology in Fastscape

### ISSUE THREAD

**Issue by Jamie534** [landlab/landlab#1261]
Hi,

I am currently working on a project which is going to look at the impact of spatially/ temporally varied lithology on river channels and drainage divides. 
Having followed some tutorials online I can set up basic layered lithology using landlab. 
I would like to model the erosion of this lithology using Fastscape proper, rather than with the Fastscape eroder within landlab. Is there a way to integrate the lithology DataArray into fastscape?

(apologies if this is a basic/ poor question, I am new to the coding game!)

Thanks, Jamie

**Comment by kbarnhart** [comment]
@Jamie534 thanks for the question. Landlab's FastscapeEroder implements the Fastscape algorithm presented by [Braun and Willet (2013)](https://www.sciencedirect.com/science/article/pii/S0169555X12004618). 

There presently isn't an interface set up between Landlab and the FastScape software packages (either python or Fortran implementations, or the xarray-simlab implementation, e.g., any of the software here https://github.com/fastscape-lem). You may be able to address this easily by passing numpy arrays back and forth, but I haven't ever done this. 

Good luck!

**Comment by Jamie534** [comment]
Thanks Katy!
I've made some good progress with landlab - its really great to use. 
I Just have a few outstanding questions which if you have any pointers on would be great.

Firstly;
How would one go about combining an imported DEM file with a litholayers component?
I have landscape evolution model running on them both separately but cannot see how I would bring them together to have a DEMs topography with an underlying varied lithology.
Secondly;
When plotting a models results with imshow_grid the default is to show the end result (say after my 1My model run). How would one specify a specific time step (or specific selection of time steps) to be shown?

Thanks Again, Jamie

**Comment by kbarnhart** [comment]
@Jamie534 I'm not sure what you mean by:

> How would one go about combining an imported DEM file with a litholayers component?
> I have landscape evolution model running on them both separately but cannot see how I would bring them together to have a DEMs topography with an underlying varied lithology.

You should be able to create a grid with a `topographic__elevation` field by importing topography from a file, and then create a Litholayers component using that grid. If your concern is that you want to create some set of structures, and don't want their thicknesses to be relative to the surface (as given by topography), but instead to be relative to some arbitrary elevation (e.g., an anticline buried under an existing mountainous topography), I think you have two options:

1. Create the layers depths (which can be spatially variable) from scratch and use the Lithology component instead of the Litholayers component.
2. Modify the Litholayers source code to take an option for considering topography in constructing the depths, and that the "layers" be defined relative to a generic surface (at present its the topography, but could be changed to be a flat plane at some arbitrary elevation). 
I think this would go something like as follows from the `__init__`:
```python
        # create layers (here listed from the top to the bottom.)
        for i in range(num_layers):

            # SOMEWHERE AROUND HERE CONSIDER THE TOPOGRAPHY 
            # IN CONSTRUCTING THE LAYER DEPTHS. 
            # WOULD NEED TO BE AN IF STATEMENT FLAG SUCH THAT CURRENT
            # BEHAVIOR IS MAINTAINED. 

            layer_depth = z_surf + z0s[i]
            layer_depth[layer_depth < 0] = 0

            layer_thickness = layer_depth.copy() - last_layer_elev.copy()

            last_layer_elev = layer_depth.copy()

            layer_thicknesses.append(layer_thickness)
            layer_ids.append(ids[i] * np.ones(z_surf.size))
```

Regarding your question: 

> When plotting a models results with imshow_grid the default is to show the end result (say after my 1My model run). How would one specify a specific time step (or specific selection of time steps) to be shown?

Landlab's grid only keeps track of the current timestep's values. If you want to make a plot of any other timesteps values you'll need to either save those values (into a numpy array with dimensions for space and time, into a series of files, into an xarray dataset), or plot within your time loop.

**Comment by Jamie534** [comment]
Sorry definitely should have proof read that before posting, 
What I mean to say is that I am trying to create a grid with an initial topography defined by an imported DEM, underlain by a lithological structure. 
As the varied lithology is exhumed I want to track how the channels are forced to evolve.

Thanks for the response, I'll see what I can put together.

Jamie

**Comment by kbarnhart** [comment]
@Jamie534 thanks for that clarification. Based on that and some thinking, I think I'd recommend the second option I've mentioned above. I don't think it would be too hard to implement, and I think it would be broadly valuable. I can't work on implementing it myself, but I'd be happy to provide guidance. 

I think the way to to this would be to add one optional argument to Litholayers which would represent the surface relative to which the structures are constructed. This option would be of the form "float, field name, or at-node array", which is a common thing we use in landlab to support multiple forms of this type of input (see the use of the function `return_array_at_node` in the Lithology component for an example of how this is used. For the moment I'll call that input "reference_surface". 


One could use a constant value in order to decouple the construction of geologic structures from the topography, as I understand you want to do. 

Then in the layer construction portion of the code it would look something like 
```python
# outside of the loop  we need to define our three at-node arrays
z_surf = function(grid.x_of_node - x0, grid.y_of_node - y0) # SHAPE OF THE STRUCTURE SURFACE 
z_topo = return_array_at_node("topographic__elevation") # TOPOGRAPHIC ELEVATION
z_reference =  return_array_at_node(reference_surface) # SURFACE STRUCTURES ARE MADE RELATIVE TO, DEFAULT IS TOPO

# inside of the loop, calculate the layer_depth values relative to the reference surface AND the topography.
# in the default option, where z_topo == z_reference we recover our initial value of (zsurf + z0s[i]) 
# where z_topo is greater than z_reference, we want to add the difference between those two values to our layer depth
# where z_topo is less than z_reference, we want to reduce the layer depth by their difference. 
# If the difference is so large that the depth is negative, then will be removed below. 

layer_depth = (z_topo - z_reference) + z_surf + z0s[i] 

layer_depth[layer_depth < 0] = 0 # where layer depth is negative, remove
```

This is just my initial guess about how this would be handled. Its probably mostly right but not quite.

**Comment by Jamie534** [comment]
@kbarnhart Thank you! I will take a look at this and see what I manage. 
My project seems to have taken a slightly different turn than I originally planned but I may still need to so this.
I have another question if you have the time? 
Do you have any suggestions on running a model set up with the lateral eroder component? 
When running my model with litholayers and stream power eroder the output landscape is what I would expect, and it runs for the complete time with no issues. However when add and run the lateral eroder component with the same setup I receive and error of 'X has a thickness of zero at at least one node', after only a few time steps. 

Thanks again, I really appreciate the time you're taking to help out!

**Comment by kbarnhart** [comment]
@Jamie534 I don't have any experience with the lateral eroder component. I'd recommend making a new issue and asking for help from Greg Tucker or Abby Langston, as they are the developers of that component. (fyi @gregtucker).

**Comment by Jamie534** [comment]
@kbarnhart thank you, will do!
