### ISSUE TITLE
Lateral Eroder Component 

### ISSUE THREAD

**Issue by Jamie534** [landlab/landlab#1264]
Hi,

I am looking for some guidance on setting up the lateral erosion component properly to allow experimenting on how varied bedrock erodibility's influence river plan forms.
The set up I currently have does not appear to make an 'sensible' topography and I am not entirely sure why. 
I have attached a copy of the code I am running (it's just a txt file with the contents copied from my jupyternotebook, hope that's ok!)
Any help or pointers on setting up the lateral eroder component to allow for experiments of channel mobility would be very much appreciated! 
(apologies it isn't a very specific query but if I'm honest I am not sure where I am going wrong in the first place!)

@gregtucker , Katy Barnhart suggested you might be the one to ask? 
Thanks for your time!  

[lateral_eroder_test.txt](https://github.com/landlab/landlab/files/5894774/lateral_eroder_test.txt)

**Comment by gregtucker** [comment]
Hi @Jamie534, for some reason I can't run your notebook (something about the text encoding), but I don't see anything obviously wrong with the code.

The world's expert in the lateral erosion component is Abby Langston (@alangston), and she might have some suggestions on reasonable parameter values and boundary conditions.

More generally, systematic experimentation is a always good way to develop a solid understanding of how and why a particular model behaves the way it does. Ultimately, if the issue you're looking out turns out to be "deep and interesting" in a scientific way, and you feel it would be beneficial to have guidance from someone who has experience in this area, then it might be appropriate to invite Abby (if she's interested), or someone else with expertise in landscape evolution modeling, to collaborate in some fashion.

**Comment by Jamie534** [comment]
Thanks @gregtucker , i'll attach a photo of the output I get after running the code I sent so you can see what is going on. 
Boundary conditions are set to closed on all but the lower edge, uplift is uniform and initial topography is a flat surface with random perturbations. 
What format should I attach the code in in the future so it may be run?

What I was expecting from the code is a recognisable drainage network to form but with the channel(s) able to migrate laterally an not just incise vertically, but given this output I don't think that is happening... 
In terms of projects, I'm hoping once I have a working model that produces a laterally eroding channel, to then add the litholayers component in to vary the bedrock and study how different configurations of bedrock might be influencing channel plan form geometry as exhumation progresses.

Thanks, Jamie 
![test_output](https://user-images.githubusercontent.com/74100206/106351225-dfa94a00-62d2-11eb-961b-2078d6cd3b4d.png)

**Comment by gregtucker** [comment]
@Jamie534 this looks like some kind of numerical problem. Suggest doing a series of tests, starting with lateral erosion *off*, running your code to steady state to make sure you can reproduce a landscape with a drainage network. Make sure your time step size is reasonable. In theory the FastscapeEroder can handle arbitrarily large steps without going unstable, but in practice in my experience an accurate transient solution requires dt < dx / (K Amax^m) where Amax is the maximum drainage area (e.g., you can use the domain size as an upper limit). Once you can reproduce something reasonable with that setup, introduce LateralEroder with a low erodibility, which you can then experiment with to try to understand its sensitivity.
