### ISSUE TITLE
Issue with landlab/utils/matrix.py in compilation

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1271]
I'm updating landlab in advance of addressing this issue in terrainbento TerrainBento/terrainbento/issues/156

I ran into an unexpected issue related to a relatively new bit of cython (the spiffy matrix utils for finite volume solutions).  

I'm on `master`, I've updated all the dependencies listed in the `requirements-XXX.txt` file. After running `make clean`, I get the following with 
`python setup.py develop`

```
gcc -bundle -undefined dynamic_lookup -L/Users/barnhark/opt/anaconda3/envs/landlab_dev/lib -arch x86_64 -L/Users/barnhark/opt/anaconda3/envs/landlab_dev/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/landlab/graph/matrix/ext/at_patch.o -o build/lib.macosx-10.9-x86_64-3.8/landlab/graph/matrix/ext/at_patch.cpython-38-darwin.so
building 'landlab.utils._matrix' extension
creating build/temp.macosx-10.9-x86_64-3.8/landlab/utils
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/barnhark/opt/anaconda3/envs/landlab_dev/include -arch x86_64 -I/Users/barnhark/opt/anaconda3/envs/landlab_dev/include -arch x86_64 -I/Users/barnhark/.local/lib/python3.8/site-packages/numpy/core/include -I/Users/barnhark/opt/anaconda3/envs/landlab_dev/include/python3.8 -I/Users/barnhark/opt/anaconda3/envs/landlab_dev/include/python3.8 -c landlab/utils/_matrix.c -o build/temp.macosx-10.9-x86_64-3.8/landlab/utils/_matrix.o
clang: error: no such file or directory: 'landlab/utils/_matrix.c'
clang: error: no input files
error: command 'gcc' failed with exit status 1
make: *** [install] Error 1
```

@gregtucker @mcflugen

**Comment by mcflugen** [comment]
@kbarnhart do you have cython installed in the environment in which you’ve installed Landlab? It looks like the .c file that cython would normally have created is missing.

**Comment by kbarnhart** [comment]
It was not installed... installing it fixed everything. 

Should cython be listed in requirements.txt? I've never had to explicitly install it before.

**Comment by mcflugen** [comment]
We list *cython* in *pyproject.toml* as part of the *build-system*, which lists the requirements needed to build *landlab* (*numpy* is also listed because we use it in *setup.py*). That should be good enough. I just tried building *landlab* in a new environment and the extensions built without me having to manually install *cython*.

I did the following:
```bash
$ conda create -n landlab python=3.8
$ conda activate landlab
$ pip install -e .
```
Is that, more-or-less, what you did as well? It would be good to try to figure out what prevented the extensions from being built (and/or why *cython* didn't get installed).

**Comment by kbarnhart** [comment]
So I didn't start from a totally clean environment. I started from the environment I've used for the past 1-2 years for landlab dev (initially created as you say above), and then updated all the dependencies with a `conda install --file=... -c conda-forge` and going through all of the requirements*.txt files. 

This environment previously didn't have any issues with cython files...

The branch passes tests, and works on a clean environment... so I think this should be considered a fluke. I'm going to close this.

**Comment by mdpiper** [comment]
I experienced the same issue as @kbarnhart. Here's the reproduce case:

1. Get a fresh clone of the landlab repo
```
$ git clone https://github.com/landlab/landlab
```
2. Follow the install instructions in the README
```
$ conda env create --file=environment-dev.yml
$ conda activate landlab_dev
$ python setup.py develop
```

Result: the build fails with
```
clang: error: no such file or directory: 'landlab/layers/ext/eventlayers.c'
clang: error: no input files
error: command '/usr/bin/clang' failed with exit code 1
make: *** [install] Error 1
```
(Note I called `make install`, which executes `python setup.py develop`.

The fix is straightforward: either follow @mcflugen's suggestion above to build with `pip install -e .` (in which case, the README and Makefile should be updated), or @kbarnhart's suggestion to include Cython in the requirements. I checked that both suggestions work. Let me know which change you prefer and I can submit a PR.

**Comment by mcflugen** [comment]
@mdpiper We should be using *pip* to install *landlab* so that *pyproject.toml* is read and the build environment—including *cython*—is set up correctly.

I don't think we would want to add *cython* to *requirements.txt* as *cython* isn't required to run *landlab*. We could, however, add it to *requirements-dev.txt*.

**Comment by mdpiper** [comment]
@mcflugen I'll send a quick PR.

**Comment by kbarnhart** [comment]
Not 100% sure of the planned scope of your PR @mdpiper, but probably worth scrubbing `python setup.py develop` from the docs/website. I'm sure that is how I installed, and that would explain my issue.

**Comment by mdpiper** [comment]
@kbarnhart Yup, that's what I'm thinking! (See upthread)

**Comment by mcflugen** [comment]
@mdpiper In your PR would you please give the entire README a quick read and edit as necessary? For instance, I noticed it says something about Python 3.8 support is coming soon! Also, backslashes instead of slashes for path names?! What?!

**Comment by mdpiper** [comment]
@mcflugen You betcha. I'll also scrub landscape.io.
