### ISSUE TITLE
Run documentation build check on PRs

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1334]
@mcflugen it doesn't look like we are enforcing documentation checks on all PRs...

Maybe there is something I'm missing in the github action logic, but I don't see it in some of the more recent PRs.

I don't think there are too many issues that have accumulated (I've just addressed a few in a forthcoming PR I'm making associated with an independent thing)... but I do think it makes sense to enforce this (in part because I know what it takes to get the docs in line if they get out of hand).

**Comment by kbarnhart** [comment]
Also it seems like the linkcheck_ignore list in conf.py is no longer used... I'll admit I'm not sure how to bring it back correctly.

**Comment by mcflugen** [comment]
@kbarnhart I've turned *linkcheck* back on in #1336. The *linkcheck_ignore* list is now used when GitHub Actions is doing the build. In the past, there were some links that appeared to be broken (but weren't) when run on Travis but I don't know if that's the case with the new build system and so maybe this list isn't even needed.

The documentation checks are only run when certain files are modified—primarily anything in the *docs* folder but also *README.rst* and similar files. I did this because the documentation check was taking a long time to complete and I wanted to make the test suite run more quickly. However, since the docs are also built from docstrings in the *landlab* folder, to be extra safe, I could turn the documentation check back on for all pull requests and not just those that modify "documentation" files. What do you think?

**Comment by kbarnhart** [comment]
@mcflugen I think it should get turned back on... Because most of the content of the documentation isn't in the docs folder, its in the docstrings. If we could put the logic on that... cool... but thats internal to a file, not by-file. 

After a few of the changes I made in #1335 the docs build without warnings (and warnings are usually formatting issues, and formatting issues often substantially impact the readability of the docs). There weren't that many warnings that were new, but there were a few. 

I see it the same way as lint, it is sorta irritating to fail a PR because of lint, but it is more irritating for one person to go in once a year and clear out all the lint. In the case of the docs I feel somewhat strongly because I was the person who fixed all the formatting warnings 🤷‍♀️ .

**Comment by mcflugen** [comment]
@kbarnhart agree 100%. It was a mistake to turn them off as, I would guess, most errors come from docstrings.

**Comment by mcflugen** [comment]
The reverse might make sense though? That is, don't run the full test suite if only documentation files have been modified.

**Comment by kbarnhart** [comment]
I don't think so, since many of our components are primarily tested through docstring examples....
