### ISSUE TITLE
editing a component vs making a new one

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#1478]
I think this may be a question for @mcflugen 
@angelmons is working on a new bedload transport function that couples with @jadams15 OverlandFlow component. 
To do the coupling, Angel had to change two variables in OverlandFlow that were initially spatially uniform to non spatially uniform - that is the variables are now fields. He also had to make one more change to the discharge mapper, which takes discharge on links and maps it to nodes.

He has coded this up in an edited version of Jordan's component with a new name. But my inclination is that this should just be an update to Jordan's component rather than a new component. Do we have rules for this?

**Comment by mcflugen** [comment]
@nicgaspar I'm not sure we have rules for this but, from what you describe, I think your intuition is correct that @angelmons' new component should really be a modification of the existing *OverlandFlow* component. If it were a separate component, there would be much repeated code—both for the components themselves as well as all of their tests—which would potentially cause maintenance headaches.

If this were to be a new component, would there ever be a reason for a user to use the existing *OverlandFlow* component?

**Comment by gregtucker** [comment]
I agree with @mcflugen that a key criterion is whether proposed new capabilities or features (a) fundamentally alter the functionality of the component, and/or (b) detract from the original component's functionality (e.g., significantly retard computational performance). If the answer to both questions is no - if an enhanced version can function just like the original with no performance penalty - then I'd say that's a clear case for a new version rather than a whole new component. That said, I can imagine some tricky edge cases related to adding fields: they might retard performance in certain cases simply by imposing additional memory demand. So then I'd say it becomes a practical question of how common such cases are, and whether the efficiency gained by having to maintain only one component instead of two outweighs any (occasional?) performance impairments due to increased memory demand. Of course, it may also be possible to engineer new fields in a clever way such that they are only created when needed (sometimes easier said than done though).

**Comment by nicgaspar** [comment]
Thank you @gregtucker and @mcflugen. I think what we will do is check the performance of the two (for now) different components. If they are similar (I think they will be), then we will just edit the original component.
Angel did change one of the mapping functions that Jordan wrote, which I think would mess up examples from her previous work. I think we can get around that by simply calling Angel's new mapping component something different.
Thanks all!
