### ISSUE TITLE
Bug in voronoi instantiations

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#159]
I am struggling to create spatially large voronoi grids.

This is fine::
    x, y = np.random.rand(nnodes), np.random.rand(nnodes)
    mg = VoronoiDelaunayGrid(x,y)

This throws the following error::
    x, y = 1000.*np.random.rand(nnodes), 1000.*np.random.rand(nnodes)
    mg = VoronoiDelaunayGrid(x,y)

=>

/Users/danhobley/git_landlab/landlab/grid/voronoi.pyc in __init__(self, x, y, reorient_links, **kwds)
    133         """
    134         if (x is not None) and (y is not None):
--> 135             self._initialize(x, y, reorient_links)
    136         super(VoronoiDelaunayGrid, self).__init__(**kwds)
    137 

/Users/danhobley/git_landlab/landlab/grid/voronoi.pyc in _initialize(self, x, y, reorient_links)
    198          self._node_at_link_head,
    199          self.active_links_ids,
--> 200          self.face_width) = self.create_links_and_faces_from_voronoi_diagram(vor)
    201 
    202         # Optionally re-orient links so that they all point within upper-right

/Users/danhobley/git_landlab/landlab/grid/voronoi.pyc in create_links_and_faces_from_voronoi_diagram(vor)
    551                 if abs(face_width[j]) >= 40000.0:
    552                     six.print_('link ' + i + ' from ' + link_fromnode[i] +
--> 553                                ' to ' + link_tonode[i] + ' has face width ' +
    554                                face_width[j])
    555                     six.print_(vor.ridge_vertices[i])

TypeError: cannot concatenate 'str' and 'int' objects

**Comment by SiccarPoint** [comment]
@gregtucker: Did you fix this yet...? You seemed to imply it would be an easy one, so thought you might just not have closed the issue.

**Comment by gregtucker** [comment]
Working on it now... we'll see how far I get before meetings kick in at 9:15...

**Comment by mcflugen** [comment]
If I remember correctly, I think the fix was to simply remove the debugging statements starting with `if abs(face_width[j]) >= 40000.0:`.

**Comment by gregtucker** [comment]
I can't reproduce the above error---it seems to work fine for me. Nonetheless I removed the offending debug code (which should have used 40 million not 40,000 in any event), and cleaned up some of the too-long comment lines.

Now, however, nosetests is giving me a pair of failing doctests, in:
landlab.grid.raster.RasterModelGrid._initialize, and
landlab.grid.raster_gradients.calculate_gradients_at_active_links

Both look like white space issues. The obvious fixes would make lines too long for PEP8... any ideas? 

I'll submit a pull request anyway (if I can figure out how).

**Comment by mcflugen** [comment]
How are you running the unit tests? Try using the `test-installed-landlab.py` instead of running `nosetests`. We shouldn't be using `nosetests` directly anymore.

**Comment by SiccarPoint** [comment]
That whitespace issue happens to me all the time, when I run nose tests locally. They aren’t “real” fails, just ignore them!

D

**Comment by gregtucker** [comment]
Ok, when I run test-installed-landlab.py instead of nosetests, I get 3 errors. One is mine, which I will try to fix in the next 5 min; the other two look like lake fill:

======================================================================
ERROR: Very simple, though possibly degerate, case, filling a 3x3 hole up to
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/gtucker/Dev/Landlab/cloned_copy/landlab/landlab/components/sink_fill/tests/test_sink_filler.py", line 280, in test_filler_flat
    assert_array_equal(hf._elev[lake], np.ones(9.))
  File "//anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 183, in ones
    a = empty(shape, dtype, order)
DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

======================================================================
ERROR: Tests a flat fill into an inclined surface, with two holes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/gtucker/Dev/Landlab/cloned_copy/landlab/landlab/components/sink_fill/tests/test_sink_filler.py", line 292, in test_filler_inclined
    np.ones(9.)*4.)
  File "//anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 183, in ones
    a = empty(shape, dtype, order)
DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

----------------------------------------------------------------------

**Comment by gregtucker** [comment]
Fix unsuccessful, will have to return to this later ... don't accept pull request for now (also, I forgot to push it back to origin, so the branch isn't up to date... I learn git one of these days...)

**Comment by SiccarPoint** [comment]
I dealt with the cases in test_sink_filler.py and committed them into your branch.

The one in test_frac… still needs your attention.

D

**Comment by gregtucker** [comment]
Ok, bug fixed and tests running ok
