### ISSUE TITLE
LinearDiffuser method='resolve_on_patches' AssertionError

### ISSUE THREAD

**Issue by chaedri** [landlab/landlab#1607]
In the LinearDiffuser component, instantiation fails when `method='resolve_on_patches'` with an AssertionError.  It also fails when `method='on_diagonals'`, as discussed in #1236, but it works with the default, `method='simple'`.

Here is a basic example that will produce the error:
```python
from landlab import RasterModelGrid
from landlab.components import LinearDiffuser

grid = RasterModelGrid((10, 10), 10)
elev = grid.add_zeros("topographic__elevation", at="node")
elev[grid.y_of_node > 120] += 10

diffusion_model = LinearDiffuser(grid, method="resolve_on_patches")
```

Environment Info:
 - Running in Ivy environment (landlab version 2.6.0) on OpenEarthScape JupyterHub

**Comment by gregtucker** [comment]
@chaedri did this issue ever get resolved?

**Comment by chaedri** [comment]
I'm not aware of any efforts to resolve this.  I tested it again this morning in the JupyterHub and got the same error.

**Comment by mcflugen** [comment]
@chaedri Sorry for the delay.

Based on the discussion in #1236, I'm tempted to simply remove the option for *"on_diagonals"* as it sounds like it wasn't working properly in *Landlab* v1.0, anyway. Is this functionality you require?

The error you are seeing when you use the *"resolve_on_patches"* option, I believe, is because the diffusion coefficient is not defined at links. If I do the following, I'm able to instantiate the linear diffuser without getting any errors.

```python
from landlab import RasterModelGrid
from landlab.components import LinearDiffuser

grid = RasterModelGrid((10, 10), 10)
elev = grid.add_zeros("topographic__elevation", at="node")
elev[grid.y_of_node > 120] += 10

kd = grid.ones(at="link") * 0.01

diffusion_model = LinearDiffuser(grid, method="resolve_on_patches", linear_diffusivity=kd)
```

The component, however, should really have been smart enough to notice that you wanted to use the *"resolve_on_patches"* method and that you provided a constant value for linear diffusivity and then assigned that constant value to every link. I can make that change but, in the meantime, could you please try something like my example above and see if the diffuser works for your use case?

**Comment by mcflugen** [comment]
@chaedri In #1693 I've changed the `LinearDiffuser` to broadcast a scalar value of the *linear_diffusivity* to a grid's links when the *resolve_on_patches* method is used. In your case, then, the diffusivity at every link will the the default value (0.01).

I've also added, I think, clearer error messages that give a user a better idea of what's going on. For example,
```python
from landlab import RasterModelGrid
from landlab.components import LinearDiffuser

grid = RasterModelGrid((10, 10), 10)
grid.add_zeros("topographic__elevation", at="node")
k = grid.ones(at="node")

diffusion_model = LinearDiffuser(grid, linear_diffusivity=k, method="resolve_on_patches")
```
gives the error
```python
ValueError: if using the resolve_on_patches method, linear_diffusivity must be defined at links.
```

I haven't dealt with `method="on_diagonals"` error yet. I'll do that in a separate pull request.

**Comment by chaedri** [comment]
@mcflugen awesome! No worries, I'm not currently using this tool but I found the issue during the ESPIn summer course. I'll mark it as resolved.
