### ISSUE TITLE
ChannelProfiler() not extracting some channels

### ISSUE THREAD

**Issue by ricsatjr** [landlab/landlab#1740]
I used ChannelProfiler for a model grid shaped by simple hillslope diffusion and stream power law. Even if minimum_channel_threshold is set to 0, some channels are not extracted/recognized by the channel profiler.  

![screen22](https://github.com/landlab/landlab/assets/11750904/e48426e0-e54f-49f4-9eb8-0cfb972dfc38)

**Comment by kbarnhart** [comment]
The channel profiler identifies channel outlets within grid.boundary nodes. However, if a basin is not fully connected to an outlet node, it may not be delineated by this method. 

Are you using the DepressionFinderAndRouter to manage depressions? My initial guess is that this behavior is because there is a depression at the base of each of those basins.

**Comment by ricsatjr** [comment]
I wasn't using the DepressionFinderAndRouter. I will try that. Thanks for the response.
