### ISSUE TITLE
ChannelProfiler: Issues arising when setting outlet nodes which aren't at the grid boundaries

### ISSUE THREAD

**Issue by eb-mars** [landlab/landlab#1753]
Hi! I'm using landlab in a planetary geomorphology context, with impact cratered topography (think: like topographic sinks in the middle of the model grid). I would like to use Channel Profiler to extract information about channels, watersheds, etc., but it by default selects outlet nodes around the grid boundaries (missing out on channels that end in craters in the middle of my grid). I tried to overcome this by setting outlet nodes = np.where(mg["drainage_area"] > area) where area is a set drainage area (e.g. 5 cells' worth of area), and using this in ChannelProfiler, but with successive model timesteps this results in shorter channels and fewer drainages, and I think it's because outlet nodes that meet that drainage area criteria are found higher and higher upstream of a channel? I was wondering if y'all have any experience with a similar issue, and any ideas of how to prevent it? or an easier/better way to "game" ChannelProfiler in this situation? Thoughts much appreciated! I know it's not a normal use case, but I think these open source tools are so powerful, so it would be great to find a way to leverage them (more) in planetary science.

**Comment by kbarnhart** [comment]
@eb-mars for your case, you will likely need to identify outlet grid cell IDs manually and provide them to outlet_nodes. You might find these nodes by identifying core nodes that have the field flow__receiver_node equal to the node id. 

Alternatively, use the TrickleDownProfiler and identify starting nodes instead of ending nodes. https://landlab.readthedocs.io/en/master/reference/components/trickle_down_profiler.html

**Comment by eb-mars** [comment]
Thank you very much! Your suggestion of identifying outlet nodes by the field 'flow__receiver_node' definitely worked much better than basing it off some minimum drainage_area, as I was trying to do before.
