### ISSUE TITLE
Standardization of attribute names/attribute-method distinction

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#219]
Still lots of places in the grid code where we lack name standardisation. My understanding is that the target forms are:

* mg.[X]_at_[Y]
* Use a property when it's not computationally intensive, and a method when it is. Also a method if you need input arguments, clearly.

A more subtle thing that I don't think we've agreed on is singular vs plural. Is it face_at_link or faces_at_links? Links_at_node/links_at_nodes?

Lots of places are lacking. This issue motivated in particular by mg.node_links(), which I think should just be mg.links_at_node.

**Comment by mcflugen** [comment]
I thought, but could definitely be wrong, we had agreed on singular. So, `node_at_cell`. However, use plural if there are more than one thing at the second thing. So, `links_at_node`.

I think a lot of this sort of thing, but not all, is fixed in some of my current pull requests. The `links_at_node`, for instance, is in #196. #194 has some other clean-up stuff.

**Comment by SiccarPoint** [comment]
Cool. I was scanning branches for it, but couldn't see it. Need to get that stuff merged ASAP after AGU!

**Comment by SiccarPoint** [comment]
This issue superseded by #240 .
