### ISSUE TITLE
Timestep explanation in the docs

### ISSUE THREAD

**Issue by jennyknuth** [landlab/landlab#232]
Somewhere in the docs, I'd like a brief discussion of timesteps and instability. Could be it's own page, but at least its own section. I'd like to link to it from the end of this section: https://github.com/landlab/landlab/wiki/Build-a-Model#5-run-the-model and maybe also from the Components page and from some of the tutorials. Here is some text we had previously on this topic: 
```
If you’ve taken a course in numerical computing, you may remember that an explicit solution to the diffusion equation requires time steps to be small; otherwise, the solution will become unstable (i.e., the numbers will go crazy and be meaningless). The Courant-Friedrichs-Lewy criterion states that the time step size must be smaller than \Delta x^2 / K_d.

With that in mind, we start by setting a value for our diffusion coefficient, ``kd``, and calculating a time-step size that is comfortably smaller than the maximum:

>>> kd = 0.01   # 0.01 m2 per year
>>> dt = 0.2*mg.dx*mg.dx/kd   # CFL condition
>>> dt
2000.0
```
```
Note that in the model without a component, we calculated a stable *dt* in the model. With the component, the testing of timestep stability happens automatically, and the component will internally subdivide the timestep as necessary. 
```

First, figure out a logical place to put this info, then write it to fit that place, then link to it from other areas.

**Comment by SiccarPoint** [comment]
That info is only relevant specifically to a couple of the components, so it’s not just a matter of transfer.

But you’re right, we need a specific section on time steps and stability.

**Comment by nicgaspar** [comment]
Yes, we should have a section on this.  But it's really most important for each of the individual components.  So we need to make sure that the documentation on each component discusses time steps.  I still think this will be tricky when making models using different components, but maybe I'm missing something obvious.

**Comment by SiccarPoint** [comment]
I’m not sure if it will be tricky as such, but it might be inefficient.

The scheme looks like this in pseudocode I think

```
c1 = Comp1()  # has a max stable tstep of, say, 2
c2 = Comp2()  # has a max stable tstep of, say, 0.1
dt = 1.
total time = 10.

for i in xrange(10):  # 10.//1.
    c1.run(dt)
        # INSIDE THE COMPONENT:
        reps = dt//2.  # == 0
        remainder = dt%2.  # == 1.
        for i in xrange(reps):
            do_the_thing(dt)
        do_the_thing(remainder)
        # ...this is inefficient
    c2.run(dt)
        # INSIDE THE COMPONENT:
        reps = dt//2.  # == 10
        remainder = dt%2.  # == 0.
        for i in xrange(reps):
            do_the_thing(dt)
        do_the_thing(remainder)
        # ...this is fine

```

Note that then the user is the one who controls how often the components “communicate” with each other, but that beyond that, the components do their own thing with whatever timestep they want. But nonsensical setting of the user defined dt (i.e., too low) will cause a lot of inefficiency.

**Comment by gregtucker** [comment]
How about something like the following:

### About Components and Time Steps

Anyone who has taken a numerical computing course knows the importance of time-step size: choose too small a step and your calculation takes forever to run; choose too big a step and it goes unstable. The details depend, of course, on the particular equations and the numerical method used to solve them.

Landlab Components are responsible for ensuring their own stability. This means, for example, that if your code asks a component to run for ten years, the component needs to make sure ten years isn't too big a step to handle. If it is, the component should subdivide the ten years into smaller steps that are stable and accurate. For example, if the component determines that one year is the biggest step it can get away with, then it should divide the requested ten-year run into ten steps of one year each. If the component uses variable-size time steps, then it should subdivide the ten years as it needs, and return when it has used up exactly ten years.

Even if each component ensures its own stability, it is still possible for a multi-component model to get into trouble by using "global" time steps that are too large. The risk arises because during each global time step, you are effectively de-coupling the components for a small interval of time. For example, suppose you have one component that calculates solar radiation on a landscape and another than calculates the resulting evapotranspiration (ET). When you run the ET component, you assume that the radiation is constant for the duration of the time step---as if the sun's position in the sky became for that period of time. That's probably a reasonable assumption if your time step is 5 minutes long, but obviously problematic if you time step is 12 hours! The moral of the story: test your model with different global time-step sizes to identify a time step that is small enough not to impact the solution in a significant way.

To learn more about time steps, numerical stability, and solution accuracy, a good source is *Numerical Recipes* by Press et al. There are also plenty of textbooks on numerical computing available.

**Comment by SiccarPoint** [comment]
Like it

**Comment by erkanistan** [comment]
This sounds reasonable..
I think there are two issue with selecting time steps: numerical 
stability and computing time and the natural realism of assuming 
constant values of a parameter within the time step. I guess the former 
is the case when we are doing simple diffusion-fluvial simulations with 
fixed parameters, but both issues need to be dealt with when doing 
complex coupling.
But I think as components get more sophisticated the time steps will 
need to reduce naturally while still being slightly different.
In the current design of the ecohydrology model the time step is storm 
duration to recharge soil moisture and produce runoff, and inter-storm 
duration to transpire, grow vegetation and decay soil moisture.. the 
model can only be used when storms are realistic at this point.. if we 
run a eco-geomorphic simulation with long storms and waiting times this 
would be a problem. Perhaps at some point we need to develop a more 
simplistic veg model for long term simulations as well but I rather 
prefer to wait for the computer to crunch numbers than use a longer time 
step to make the model more effective..

**Comment by jennyknuth** [comment]
Nice! We now have a page to reference here:
https://github.com/landlab/landlab/wiki/Time-Steps

On Tue, Dec 29, 2015 at 9:52 AM, Dan Hobley <notifications@github.com>
wrote:

> Like it
>
>
> > On 29 Dec 2015, at 16:49, Greg Tucker <notifications@github.com> wrote:
> >
> > How about something like the following:
> >
> > About Components and Time Steps
> >
> > Anyone who has taken a numerical computing course knows the importance
> of time-step size: choose too small a step and your calculation takes
> forever to run; choose too big a step and it goes unstable. The details
> depend, of course, on the particular equations and the numerical method
> used to solve them.
> >
> > Landlab Components are responsible for ensuring their own stability.
> This means, for example, that if your code asks a component to run for ten
> years, the component needs to make sure ten years isn't too big a step to
> handle. If it is, the component should subdivide the ten years into smaller
> steps that are stable and accurate. For example, if the component
> determines that one year is the biggest step it can get away with, then it
> should divide the requested ten-year run into ten steps of one year each.
> If the component uses variable-size time steps, then it should subdivide
> the ten years as it needs, and return when it has used up exactly ten years.
> >
> > Even if each component ensures its own stability, it is still possible
> for a multi-component model to get into trouble by using "global" time
> steps that are too large. The risk arises because during each global time
> step, you are effectively de-coupling the components for a small interval
> of time. For example, suppose you have one component that calculates solar
> radiation on a landscape and another than calculates the resulting
> evapotranspiration (ET). When you run the ET component, you assume that the
> radiation is constant for the duration of the time step---as if the sun's
> position in the sky became for that period of time. That's probably a
> reasonable assumption if your time step is 5 minutes long, but obviously
> problematic if you time step is 12 hours! The moral of the story: test your
> model with different global time-step sizes to identify a time step that is
> small enough not to impact the solution in a significant way.
> >
> > To learn more about time steps, numerical stability, and solution
> accuracy, a good source is Numerical Recipes by Press et al. There are also
> plenty of textbooks on numerical computing available.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/landlab/landlab/issues/232#issuecomment-167828529>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/landlab/landlab/issues/232#issuecomment-167828955>.
>



-- 

Full-Stack Web Developer
303-802-7214
http://jennyknuth.com
https://www.linkedin.com/in/jennyknuth
https://github.com/jennyknuth

**Comment by SiccarPoint** [comment]
You’re totally right Erkan. To some extent I think users need to have enough skill to think these issues out for themselves, but we probably should talk about it in the docs nonetheless.

I wonder if a possible way forward (down the line!) for you ecohydro component would be to import the storm generator internally and demand the user supplies input params to initialise it, within appropriate bounds that you can control. Then if the external timestep is set too long, you can still chunk it up more appropriately internally using the storm generator you have control of.

**Comment by jennyknuth** [comment]
Replied before I saw these comments…you guys are fast! Erkan, do you want to add a bit about realism to the page here: https://github.com/landlab/landlab/wiki/Time-Steps? (Just click the edit button at the top to make changes.) Dan, your bit is critical for people writing components.
