### ISSUE TITLE
Cells vs. nodes in fields

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#29]
Grid[‘cell’][‘name’] == Grid[‘node’][‘name’][grid.core_nodes], and at the moment it isn’t. Both node & cell (and link & face) should point at the same addresses.

**Comment by SiccarPoint** [comment]
One year later, I find myself wondering if the user can gain control over this at instantiation time? i.e., they can be implicitly linked for some grids, but not on others.

I find myself almost always wanting to work on nodes/links, so am not super invested in this...

**Comment by mcflugen** [comment]
I think that values at nodes and values at cells are, in general, different. If they are ever the same, then that's just by coincidence.

1. If they were the same by definition then why even differentiate the two?
2. Some nodes don't even have cells.

Adding this linkage of values-at-cells and values-at-nodes to landlab grids would add significant complexity to the code and I'm not sure a lot of people would even use it. 

We should, however, provide mapping functions so that users can do this sort of mapping themselves. In fact, we already have many of these mapping functions (in `landlab.grid.mappers`).

**Comment by saisiddu** [comment]
I agree that values at nodes and values at cells should be different. Also, mapping should be purely via mappers and/or similar approaches but not by default. I use cellular grids mostly. So please do let us know if anything is changing regarding cells/cellular grids.

________________________________

**Comment by SiccarPoint** [comment]
Had no idea about the mappers. Eric, you must do a better job at showing us all the cool stuff you designed! ;-)

Looks good to me then. Looks like the mappers do exactly what I was envisioning.
