### ISSUE TITLE
Landlab hangs if lake routing is attempted with n!=1

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#444]
This appears to be related to #431, but is a distinct issue I think. I will try to mock up a gist to reproduce the issue...

**Comment by gregtucker** [comment]
I suspect issue 431 as you note. That problem was to do with taking a fractional power of a negative # in the stream power solver, leading to NaNs and an infinite loop in the stream power solution loop. I *thought* I had merged but looking at code it appears not. Try merging PR #433, see if that does the trick.
(sent from Arlington where the SI2 PI meeting kicks off tomorrow morning...)

**Comment by SiccarPoint** [comment]
Problem is fixed by @gregtucker's fix for #431. Closing.

**Comment by awickert** [comment]
Sorry, Dan -- I had an old v1.0 hanging around on my computer and taking the default spot, when I thought that I was really using the most up-to-date version. All fixed here too.

**Comment by SiccarPoint** [comment]
No worries. Glad everything's OK now!
