### ISSUE TITLE
Creating and using conda environments on windows

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#500]
Date: 13 Jun 2017 
Author: Sai Nudurupati
I am writing this post to serve as a reference to create and use python versions created using Conda environments. 
Assumption: Windows 10 machine is used (may be true for other Windows versions)
Example: Create an Anaconda Python 3.5 version on a machine that has an installed Anaconda Python 2.7 version already.

Steps to create a conda environment:
1. Open Anaconda Prompt (I prefer Anaconda Prompt to cmd)
2. Create conda environment named 'python_3_5:
$  conda create -n python_3_5 python=3.5 anaconda
3.  Activate this environment:
$ activate python_3_5
4. Access this Python:
$ C:\Users\UserName\Anaconda\envs\python_3_5\python.exe
5. Deactivate this environment:
$ deactivate python_3_5
6. Remove this environment:
$ conda remove -n python_3_5 --all

At any time, if you want to check all available environments:
$ conda info -e

Good references:
-> https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/
-> https://www.continuum.io/blog/developer-blog/python-packages-and-environments-conda

**Comment by Owaisaaa** [comment]
I have created the conda environment and installed the tensorflow in it. Now when I open Jupiter Notebook and try to execute my file it shows me an error.
"no module named tensorflow"
Kindly suggest

**Comment by saisiddu** [comment]
Hi Owaisaaa, I am afraid this issue is not related to Landlab package. Please correct me if I am wrong.

- you may want to check if you have installed tensor flow in the right environment. If yes, check if  jupyter notebook needs extra steps to take in tensor flow. For such issues, I generally check stackoverflow (stackoverflow.com).

**Comment by mcflugen** [comment]
@Owaisaaa Did you start up Jupyter Notebook in the same environment that you installed tensorflow in (and did you install Jupyter notebook in that environment)?

You need to:
* Create a new environment
* Activate that environment
* Install tensorflow in that environment
* Install Jupyter in that environment
* Run Jupyter notebook in that environment

Note that you need to activate your environment whenever you start a new shell. Otherwise, you'll be put back in your root environment.

There is some great documentation on using conda environments [here](https://conda.io/docs/user-guide/tasks/manage-environments.html).

This may also be a problem with tensorflow, in which case this should really be a question for the tensorflow team.

**Comment by Owaisaaa** [comment]
Really thankful to you.
God bless
