### ISSUE TITLE
Strange landscapes when m/n > 0.5

### ISSUE THREAD

**Issue by fclubb** [landlab/landlab#515]
Hi,
I'm doing a series of runs with just simple detachment-limited stream power and varying m/n between 0.2 and 0.8 (keeping n constant at 1 and just varying m). I get weird landscapes when m/n is greater than 0.5, where the channels become extremely linear and diagonal - just wondering if you have had any issues with this, or have any idea how to fix it?
I'm running a 50 by 50km model domain with 30m grid resolution, and just simple stream power to steady state (running for 5 Ma with a timestep of 5 kyr, and uplift of 0.01 m/yr).
I've tried updating to the latest conda version and re-running and I get the same effect.
Thanks,
Fiona
![sp_model_mn_06](https://user-images.githubusercontent.com/12732264/28632023-0c66b1a4-7227-11e7-9098-51f2c48f95a8.png)

**Comment by kbarnhart** [comment]
@fclubb Thanks for making an issue of this. 

This isn't something we've discussed recently, so I don't think its a known issue. If I'm wrong about this, I suspect someone else will chime in and correct me. 

Could you please provide a minimally complete example (https://stackoverflow.com/help/mcve for more info) that reproduces this sort of landscape so we can better look into the problem.

**Comment by nicgaspar** [comment]
@fclubb Interesting. If I had to guess there is no "bug" in Landlab, but rather this results from the way the equations are implemented. Are you getting the correct analytical solution? If not, then it is definitely a bug. If you are, it could still be a bug, but it is less obvious and maybe something to do with the flow router? (Not sure.)

Is this organization a problem? You could try adding hillslopes and it might go away. You could also try forcing an organization that you like by generating a landscape with a different m/n, and then using that landscape as the initial condition for m/n  > 0.5.

Shelef and Hilley might have some insight into this, although I'm not sure they get the same result that you are seeing. GRL, 2014, 10.1002/2014GL059816

**Comment by kbarnhart** [comment]
@nicgaspar to test the analytical solution @fclubb would run the model to steady state and then make a slope-plot and verify that the scaling relationship is what is is predicted by the values of m and n she used. Right?

I'm curious which flow direction method @fclubb is using. In FlowRouter (the old soon to be deprecation-flagged component) it is D8 while in FlowAccumulator it is D4.

**Comment by nicgaspar** [comment]
@kbarnhart @fclubb Yes, exactly, verify the slope-area scaling at steady state. Remember it's not just the concavity that should be verified (so a function of m/n), but also verify that channel steepness is correct (function of incision/uplift rate and rock erodibility).

That looks to me like it is D8, but it's hard to tell at this scale.

**Comment by fclubb** [comment]
It's D8 flow routing I think, for each model step I run the flow router and fastscape eroder like this:

```python
   # instantise the components
    fr = FlowRouter(mg, **inputs)
    sp = FastscapeEroder(mg, **inputs)
    imgs = []

    # run the model
    for i in range(nt):
        # run the flow routing and stream power
        ts = i*dt
        fr.run_one_step()
        sp.run_one_step(dt)
        mg.at_node['topographic__elevation'][mg.core_nodes] += uplift_per_step # add the uplift
```
I don't explicitly state the flow routing method so it's the default setting (I assumed this was D8 based on the docs).

Thanks for your suggestions @nicgaspar, I'm running these models specifically to test methods of detecting basin concavity so this will be the next thing I do.  I'm running the SA plots at the moment so we'll see what they show in terms of identified concavity and k_sn.

**Comment by kbarnhart** [comment]
@fclubb could you add a bit more code that includes instantiating the model grid and setting the value of the inputs dictionary and uplift_per_step so I can try and reproduce your results? 

Unless the inputs dictionary sets the method to D4, then this code would use D8 flow directions.

**Comment by fclubb** [comment]
@kbarnhart Yes sure, here's an edited-down version of my function that should have the essentials. I've also attached my input parameter file.
[params_steady_state_50km.txt](https://github.com/landlab/landlab/files/1177614/params_steady_state_50km.txt)

```python
def run_stream_power_model(path,param_file):
    """
    Function to actually run the model. Uses FastscapeEroder to simulate stream power and runs to steady state
    """
    # read the input parameter file
    input_file = path+param_file
    inputs = load_params(input_file)
    # print the parameter file
    print(inputs)

    #load inputs into lists
    nrows = inputs['nrows']
    ncols = inputs['ncols']
    dx = inputs['dx']
    uplift_rate = inputs['start_uplift_rate']
    total_t = inputs['total_time']
    dt = inputs['dt']

    nt = int(total_t // dt) # how many loops we need
    uplift_per_step = uplift_rate * dt

    # create a raster grid
    mg = RasterModelGrid((nrows,ncols), dx)
    z = mg.add_zeros('node','topographic__elevation')
    # add some roughness to let natural channels develop
    initial_roughness = np.random.rand(z.size)/100000.
    z += initial_roughness

    # set the boundary conditions
    for edge in (mg.nodes_at_left_edge, mg.nodes_at_right_edge):
        mg.status_at_node[edge] = CLOSED_BOUNDARY
    for edge in (mg.nodes_at_bottom_edge,mg.nodes_at_top_edge):
        mg.status_at_node[edge] = FIXED_VALUE_BOUNDARY

    # instantise the components
    fr = FlowRouter(mg, **inputs)
    sp = FastscapeEroder(mg, **inputs)

    # run the model
    for i in range(nt):
        # run the flow routing and stream power
        ts = i*dt
        fr.run_one_step()
        sp.run_one_step(dt)
        mg.at_node['topographic__elevation'][mg.core_nodes] += uplift_per_step # add the uplift
```

**Comment by kbarnhart** [comment]
@fclubb Thanks for the code and input files!

I'm working to recreate the example you've provided. I did some cut and paste so that the example can be run more easily -- let me know if you think I've added any errors. The code is below.

When I run this, it looks like it has 1000 time steps which take approximately 14 seconds on my computer (an estimated total of 4 hours). I'll run it overnight to see if I reproduce your plots, but if there is a parameter set that reproduces your problem and could be run in less than 10 minutes, that would be great. I suspect that decreasing the grid size would be the best way forward. 

I have an idea about what may be causing this problem. I'm testing it overnight and I'll let you know what I find. 

```python
# import necessary modules. 
from landlab import RasterModelGrid
from landlab import CLOSED_BOUNDARY, FIXED_VALUE_BOUNDARY
from landlab.components import FlowRouter, FastscapeEroder
from landlab.plot import imshow_grid
import numpy as np
import matplotlib.pylab as plt

# inputs 
nrows = 1666
ncols = 1666
dx = 30
dt = 5000
total_t = 5000000
uplift_rate = 0.01
K_sp = 0.0005 
m_sp = 0.6
n_sp = 1.

# calculate number of timesteps and uplift per timestep. 
nt = int(total_t // dt) # how many loops we need
uplift_per_step = uplift_rate * dt

# create a raster grid
mg = RasterModelGrid((nrows,ncols), dx)
z = mg.add_zeros('node','topographic__elevation')
# add some roughness to let natural channels develop
initial_roughness = np.random.rand(z.size)/100000.
z += initial_roughness

# set the boundary conditions
for edge in (mg.nodes_at_left_edge, mg.nodes_at_right_edge):
    mg.status_at_node[edge] = CLOSED_BOUNDARY
for edge in (mg.nodes_at_bottom_edge,mg.nodes_at_top_edge):
    mg.status_at_node[edge] = FIXED_VALUE_BOUNDARY

# instantise the components
fr = FlowRouter(mg)
sp = FastscapeEroder(mg, K_sp=K_sp, m_sp=m_sp, n_sp=n_sp)

# run the model
for i in range(nt):
    # run the flow routing and stream power
    ts = i*dt
    fr.run_one_step()
    sp.run_one_step(dt)
    mg.at_node['topographic__elevation'][mg.core_nodes] += uplift_per_step # add the uplift
    print(i, nt)

plt.figure()
imshow_grid(mg, mg.at_node['topographic__elevation'])
plt.show()

plt.figure()
plt.loglog(mg['node']['drainage_area'], mg['node']['topographic__steepest_slope'], '.')
plt.show()
```

**Comment by fclubb** [comment]
Thank you @kbarnhart, I really appreciate the help! I've tried with a smaller model domain and was seeing a similar pattern although not as well developed, here's the parameters (m/n in this run was 0.8)
```python
nrows = 100
ncols = 100
dx = 30
dt = 5000
total_t = 5000000
uplift_rate = 0.01
K_sp = 0.0005 
m_sp = 0.8
n_sp = 1.
```
That setup runs for me in about 30 seconds so hopefully it should be much easier to work with.

**Comment by kbarnhart** [comment]
@fclubb perfect. 

I can reproduce the pattern by running the code (either for the total time or 10x the total time). Some figures.

Topography:
![standard_topo](https://user-images.githubusercontent.com/6589339/28675066-f661f85a-72a3-11e7-876c-f9f32fd47df9.png)

Slope Area Relationship:
![standard_slope_area](https://user-images.githubusercontent.com/6589339/28675070-f98ec59e-72a3-11e7-92c7-5145bb3db4ba.png)

Slope Map:
![standard_slope](https://user-images.githubusercontent.com/6589339/28675084-031a3a3a-72a4-11e7-9d8c-675a4cac6a26.png)

Where Slope-Area is out of equilibrium:
![standard_topo_where_unsteady](https://user-images.githubusercontent.com/6589339/28675092-093cce8c-72a4-11e7-8ff6-16deaf151f2e.png)

As you can see we can confirm that the unsteady portions are at the boundary where you'd imposed the uplift boundary condition. This makes sense. (Code for these figures below in snippet #1 ). I changed the loop to ```nt*10``` and found the same linear pattern you brought up. 

I was able to make the problem go away by adding one component -- the DepressionFinderAndRouter component which is run to find and route water through depressions. (Code snippet #2, same figures as above pasted below). 

If you run it, you'll see that the first few time steps take a lot longer than the later ones, this is because the random initial topography has a lot of pits that require the lake mapper to find and re-route. I can tell you that the lake mapper will take a really long time on your 1666x1666 sized grid (I tried it...). 

Topography:
![lake_mapper_topo](https://user-images.githubusercontent.com/6589339/28674979-b51b1908-72a3-11e7-9c07-a15bb31a0a2d.png)

Slope Area Relationship:
![lake_mapper_slope_area](https://user-images.githubusercontent.com/6589339/28674977-b4fbabea-72a3-11e7-930c-293fe5a86cfd.png)

Slope Map:
![lake_mapper_slope](https://user-images.githubusercontent.com/6589339/28674980-b51d9714-72a3-11e7-993c-1703c27ce49c.png)

Where Slope-Area is out of equilibrium:
![lake_mapper_topo_where_unsteady](https://user-images.githubusercontent.com/6589339/28674978-b5154ffa-72a3-11e7-98d8-2e060c7f00aa.png)

Now the real question... Why is this the case. I think it is because of how the drainage network evolves when you do and don't map depressions. I've made gifs of the first 70 time steps that show log(drainage_area+1) 

Early Evolution of Drainage Area:
Without Lake Mapper:
![withoutlakemapper](https://user-images.githubusercontent.com/6589339/28676235-5fade3a2-72a7-11e7-954a-5ac168fc659a.gif)

With Lake Mapper
![withlakemapper](https://user-images.githubusercontent.com/6589339/28676241-62374d20-72a7-11e7-912c-fc2e8a29bd8c.gif)

Code snippet #1 : Original code. 
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 26 15:54:43 2017

@author: barnhark
"""
import time

# import necessary modules. 
from landlab import RasterModelGrid
from landlab import CLOSED_BOUNDARY, FIXED_VALUE_BOUNDARY
from landlab.components import FlowRouter, FastscapeEroder
from landlab.plot import imshow_grid
import numpy as np
import matplotlib.pylab as plt

# inputs 
nrows = 100
ncols = 100
dx = 30
dt = 5000
total_t = 5000000
uplift_rate = 0.01
K_sp = 0.0005 
m_sp = 0.8
n_sp = 1.

# calculate number of timesteps and uplift per timestep. 
nt = int(total_t // dt) # how many loops we need
uplift_per_step = uplift_rate * dt

# create a raster grid
mg = RasterModelGrid((nrows,ncols), dx)
z = mg.add_zeros('node','topographic__elevation')
# add some roughness to let natural channels develop
np.random.seed(seed=9087)
initial_roughness = np.random.rand(z.size)/100000.
z += initial_roughness

# set the boundary conditions
for edge in (mg.nodes_at_left_edge, mg.nodes_at_right_edge):
    mg.status_at_node[edge] = CLOSED_BOUNDARY
for edge in (mg.nodes_at_bottom_edge,mg.nodes_at_top_edge):
    mg.status_at_node[edge] = FIXED_VALUE_BOUNDARY

# instantise the components
fr = FlowRouter(mg)
sp = FastscapeEroder(mg, K_sp=K_sp, m_sp=m_sp, n_sp=n_sp)

# run the model

starttime = time.time()

for i in range(nt*10):
    # run the flow routing and stream power
    ts = i*dt
    fr.run_one_step()
    sp.run_one_step(dt)
    mg.at_node['topographic__elevation'][mg.core_nodes] += uplift_per_step # add the uplift
    
    now = time.time()
    elapsed = now-starttime
    
    per_step = elapsed/float(i+1)
    estimated = (per_step*nt)/60./60.
    print(i, nt, np.round(per_step, decimals=3), estimated)

# Make some plots

# make a plot of the topography
plt.figure()
imshow_grid(mg, mg.at_node['topographic__elevation'])
plt.savefig('standard_topo.pdf')
plt.show()

# make a slope-area plot
detachment_predicted_slope = (uplift_rate/(sp.K*(mg['node']['drainage_area']**sp.m)))**sp.n

plt.figure()
plt.loglog(mg['node']['drainage_area'], detachment_predicted_slope, 'k-')
plt.loglog(mg['node']['drainage_area'][mg.core_nodes], mg['node']['topographic__steepest_slope'][mg.core_nodes], '.')
plt.xlabel('Drainage Area')
plt.ylabel('Slope')
plt.legend(['Detachment Limited Theory', 'Model'])
plt.savefig('standard_slope_area.pdf')
plt.show()

# we can see that the except a few nodes where the slope is too big for the drainage area, everything is in equilibrium. 
# plotting the slope we can see this is right next to the boundary where uplift condition was just applied. 

# first we see that the high slopes (of >1) are only at the boundary
plt.figure()
imshow_grid(mg, mg.at_node['topographic__steepest_slope'])
plt.savefig('standard_slope.pdf')
plt.show()

# and second we can plot 
slope_diff = mg['node']['topographic__steepest_slope']-detachment_predicted_slope
slope_diff[np.isinf(slope_diff)] = 0
not_steady = np.where(np.abs(slope_diff)>0.1)[0]

plt.figure()
imshow_grid(mg, mg.at_node['topographic__elevation'])
plt.plot(mg.x_of_node[not_steady], mg.y_of_node[not_steady], 'r.')
plt.savefig('standard_topo_where_unsteady.pdf')
plt.show()

# so we can confirm that even though this grid has the wierd drainage pattern, 
# it has reached a steady state slope-area relationship. 
```

Code Snippet #2 
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 26 15:54:43 2017

@author: barnhark
"""
import time

# import necessary modules. 
from landlab import RasterModelGrid
from landlab import CLOSED_BOUNDARY, FIXED_VALUE_BOUNDARY
from landlab.components import FlowRouter, FastscapeEroder, DepressionFinderAndRouter
from landlab.plot import imshow_grid
import numpy as np
import matplotlib.pylab as plt

# inputs 
nrows = 100
ncols = 100
dx = 30
dt = 5000
total_t = 5000000
uplift_rate = 0.01
K_sp = 0.0005 
m_sp = 0.8
n_sp = 1.

# calculate number of timesteps and uplift per timestep. 
nt = int(total_t // dt) # how many loops we need
uplift_per_step = uplift_rate * dt

# create a raster grid
mg = RasterModelGrid((nrows,ncols), dx)
z = mg.add_zeros('node','topographic__elevation')
# add some roughness to let natural channels develop
np.random.seed(seed=9087)
initial_roughness = np.random.rand(z.size)/100000.
z += initial_roughness

# set the boundary conditions
for edge in (mg.nodes_at_left_edge, mg.nodes_at_right_edge):
    mg.status_at_node[edge] = CLOSED_BOUNDARY
for edge in (mg.nodes_at_bottom_edge,mg.nodes_at_top_edge):
    mg.status_at_node[edge] = FIXED_VALUE_BOUNDARY

# instantise the components (we could use the FlowAccumulator, but for consistency with original code, I've stuck with the FlowRouter+ DepressionFinderAndRouter combination.)

fr = FlowRouter(mg)
sp = FastscapeEroder(mg, K_sp=K_sp, m_sp=m_sp, n_sp=n_sp)
df = DepressionFinderAndRouter(mg)

# run the model

starttime = time.time()

for i in range(nt):
    # run the flow routing and stream power
    ts = i*dt
    fr.run_one_step()
    df.map_depressions()
    sp.run_one_step(dt)

    mg.at_node['topographic__elevation'][mg.core_nodes] += uplift_per_step # add the uplift
    
    now = time.time()
    elapsed = now-starttime
    
    per_step = elapsed/float(i+1)
    estimated = (per_step*nt)/60./60.
    print(i, nt, np.round(per_step, decimals=3), estimated)

# make a plot of the topography
plt.figure()
imshow_grid(mg, mg.at_node['topographic__elevation'])
plt.savefig('lake_mapper_topo.pdf')
plt.show()

# make a slope-area plot
detachment_predicted_slope = (uplift_rate/(sp.K*(mg['node']['drainage_area']**sp.m)))**sp.n

plt.figure()
plt.loglog(mg['node']['drainage_area'], detachment_predicted_slope, 'k-')
plt.loglog(mg['node']['drainage_area'][mg.core_nodes], mg['node']['topographic__steepest_slope'][mg.core_nodes], '.')
plt.xlabel('Drainage Area')
plt.ylabel('Slope')
plt.legend(['Detachment Limited Theory', 'Model'])
plt.savefig('lake_mapper_slope_area.pdf')
plt.show()

# we can see that the except a few nodes where the slope is too big for the drainage area, everything is in equilibrium. 
# plotting the slope we can see this is right next to the boundary where uplift condition was just applied. 

# first we see that the high slopes (of >1) are only at the boundary
plt.figure()
imshow_grid(mg, mg.at_node['topographic__steepest_slope'])
plt.savefig('lake_mapper_slope.pdf')
plt.show()

# and second we can plot 
slope_diff = mg['node']['topographic__steepest_slope']-detachment_predicted_slope
slope_diff[np.isinf(slope_diff)] = 0
not_steady = np.where(np.abs(slope_diff)>0.1)[0]

plt.figure()
imshow_grid(mg, mg.at_node['topographic__elevation'])
plt.plot(mg.x_of_node[not_steady], mg.y_of_node[not_steady], 'r.')
plt.savefig('lake_mapper_topo_where_unsteady.pdf')
plt.show()
```

**Comment by SiccarPoint** [comment]
Nice stuff @kbarnhart!

**Comment by fclubb** [comment]
Thanks so much for your help @kbarnhart!  That's super useful, and much appreciated.
I'll try re-running my grids with the DepressionFinderAndRouter.  Just FYI I also tried re-running adding in linear hillslope diffusion which also seems to stop the strange linear pattern (see fig below)

*Same param setup, just adding hillslope diffusion*
![sp_model_10km_ts_4500000](https://user-images.githubusercontent.com/12732264/28678143-80175cfa-72e7-11e7-8840-0972bb47bafc.png)

Do you think in your experience that this would take less runtime than the DepressionFinderAndRouter? Although I'm guessing it's important to have to make sure I don't have a lot of problems with pits and sinks in the resulting DEMs as well...

**Comment by kbarnhart** [comment]
@fclubb I'd recommend thinking about what components you need to simulate the processes you want to be simulating rather than including a component to make the model run faster (or slower...). The components I'd use a the most basic landscape evolution model would be the FlowRouter and DepressionFinderAndRouter (see note below), some sort of channel incision (e.g. FastscapeEroder) and some sort of hillslope diffusion (e.g linear diffusion). But ultimately the appropriate component choices will be dictated by the scientific questions you are trying to answer. 

One way to consider the linear features you brought up is that they are a **property** of the landscape evolution model you made (the one without the depression finder). Whether they are reasonable depends on what you are simulating. If you are simulating a landscape that can make water disappear in local pits (e.g. karst?), they should be considered an artifact of the model structure.  

Regarding speed, as a rule of thumb, the more pits there are (and the bigger their contributing lake area), the slower the DepressionFinderAndRouter will be. We have some ideas on how to improve this, but I've just not had the time to implement them... If for your initial random topography, running hillslope diffusion removes some pits (which I suspect it would do), it may speed up the DepressionFinderAndRouter, but that is certainly worth testing (if you are going to be doing any number of long runs I recommend profiling your code. https://docs.python.org/2/library/profile.html)

Finally a comment related to speed. The FlowRouter has recently been superseded by a new component called the FlowAccumulator. If specified correctly, the FlowAccumulator can run the DepressionFinder within its run_one_step() method and under certain conditions this can result in substantial speedups for this part of the code. I'm in the middle of writing a tutorial to discuss best-practices for using the FlowAccumulator to make code faster (and making some changes to put up formal deprecation warnings for FlowRouter). I'd highly recommend that you check out the documentation for the FlowAccumulator and the tutorials I've already made about the FlowAccumulator that give examples of using it.

**Comment by fclubb** [comment]
Thanks @kbarnhart, I really appreciate your help on this!
