### ISSUE TITLE
Confusing ways to add paths to documentation

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#569]
About: landlab/docs
What is confusing?
   - compare 
         > https://github.com/landlab/landlab/blob/master/docs/landlab.components.rst
         > https://github.com/landlab/landlab/blob/master/docs/landlab.utils.rst
         > https://github.com/landlab/landlab/blob/master/landlab/utils/decorators.py

The way we add ::toctree:: is a little confusing. Please suggest the modules that I need to check to understand this. Should I be looking at documentation for 'sphinx'?  Thanks!

Also, why do we not setup our documentation to update every time 'master' is updated? How do I preview the changes I make to the documentation?

**Comment by saisiddu** [comment]
Also, why shouldn't we update our documentation every time we edit 'master'? Will that not be faster? How do I preview the changes I make to documentation?

**Comment by SiccarPoint** [comment]
I'm not entirely sure what you're asking, Sai. Updating the autodocs is a bit of a dark art. My best advice is to get googling if you want to actually get on top of this; I pieced it together from fragments of useful information spread across 5 or 6 sites. It will also be instructive to make a branch you can just delete later and start messing around with the existing files, to see what changes break what. You'll I think find that several of our `.rst` files are in fact now orphaned, and can only be accessed through the web by actually entering the url. I *think* this includes `land lab.components.rst` above, though I see we're still updating it regardless.

In practical terms, best advice is to just copy what you see. Looking at things in github (as above) will confuse you though, as it partially renders any `.rst` files it finds. If you want to see the actual file for these, click `raw`. A brief summary would be that any time you see a `.. automodule`, this tells the file to find the named component file (i.e., `.py` file) and strip the docstrings found there. Conversely, any time you see a `.. toctree`, this is telling the doc compiler to go to the **.rst** file named, and fill in the section (and create hyperlinks) using the info it finds in _that_ file. So you can debug any docs that don't look right by following that trail.

Remember that I messed with the specific grid documentation files so that they properly update themselves and create some order in the method madness. Should you ever add new grid methods, you can use ``LLCATS`` (see any existing grid method) to add it to the grid docs appropriately.

Finally, we do, in fact, rebuild the docs at every commit. However, when you click through to the auto-built docs on the web, by default it shows you the "latest" version. This is a stupid misnomer; this is actually the documentation associated with the last release version. If you want to see the bleeding edge, `master` docs, use the toggle in the bottom right to switch from "latest" to "master". However, if you're playing with doc changes, better to do this in a branch, then build the docs locally to look at. To do this, navigate to `landlab/docs` and from a command prompt run `build html` (presumably this is the same on windows...? Eric may know what to do if not). This will dump a version of the site into your local `landlab/docs/_build/html` for your viewing pleasure. Note the homepage is in `index.html`, and all the links will work from there.

Now I've written all this, I should probably make a docs page out of it!

**Comment by saisiddu** [comment]
Wow! Thanks a lot Dan! I got confused with the orphaned rst files then. I will strictly follow the instructions in the link you pointed out to in the other issue. And thanks for the instructions to build these on local machine.
