### ISSUE TITLE
Radiation 2d plot

### ISSUE THREAD

**Issue by ELEGER** [landlab/landlab#624]
Hello,
I'm trying to plot the radiation on a 2D grid, however, I'm failling quite strongly.
For some reason since the radiation is computed on a grid from a DEM, it should be possible to use imshow_grid_at_node/cell depending what you want.

```

rad = Radiation(watershed, method='Grid', latitude=34)

rad.var_mapping

(('topographic__elevation', 'node'),
 ('radiation__incoming_shortwave_flux', 'cell'),
 ('radiation__net_shortwave_flux', 'cell'),
 ('radiation__ratio_to_flat_surface', 'cell'))



imshow_grid_at_node(rad,'radiation__net_shortwave_flux'),

AttributeError: 'Radiation' object has no attribute 'at_node'

imshow_grid_at_cell(rad,'radiation__net_shortwave_flux'),

AttributeError: 'Radiation' object has no attribute 'at_cell'

```

Sorry for this dumb question...

Thanks in advance for you help,

e

**Comment by kbarnhart** [comment]
@ELEGER , thanks for the question.

I'd recommend that you use `imshow_grid` rather than `imshow_grid_at_node` or `imshow_grid_at_cell` as these methods have been depreciated. 

I'd recommend taking a look at the  section of the landlab wiki about plotting: http://landlab.readthedocs.io/en/release/landlab.plot.html

All three of these methods expect that the first argument is a landlab grid instance. For example:
```python
imshow_grid(grid, values, **kwargs)
```

You are passing the Radiation component in the place `imshow_grid_at_node` is expecting a grid when you write :
```python
imshow_grid(rad, **kwargs)
```

Feel free to ask any additional questions as you get your plot to work. 

If you have questions about the specifics of the Radiation component, I'd recommend you tag @saisiddu .

**Comment by ELEGER** [comment]
Thank you Katy,
e.

**Comment by kbarnhart** [comment]
@ELEGER 

Quick clarification, I mistyped when I wrote that `imshow_grid_at_node` and `imshow_grid_at_cell` had been deprecated. They have not been deprecated and we don't have plans to deprecate them. 

`imshow_cell_grid` and `imshow_node_grid` are the functions that were deprecated. sorry about that.

**Comment by ELEGER** [comment]
No prob.
I've seen in the source codes many version of them, imshow, imshow_cell_grid *_node and so on, the helps header are not all updated. It's allright, perfectly normal to make it better day after days. 
Thanks for your clarification
e
