### ISSUE TITLE
Can't install land lab due to specification conflict between landlab and numba

### ISSUE THREAD

**Issue by travisclow** [landlab/landlab#631]
Hi,

I'm on a fresh install of the latest version of Anaconda (had to reinstall because Jupyter Notebook stopped launching/working after trying to update a previous, working install of Landlab).

I'm trying to install landlab (after a successful uninstall) and keep getting this error:

> clow~ conda install landlab -c landlab
> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - landlab
>   - numba
> Use "conda info <package>" to see the dependencies for each package.
> 

Any ideas on how to fix this? It says that landlab is in conflict with numba, so it almost seems like my uninstall of landlab before uninstalling and reinstalling a fresh version of Anaconda did not work... however, when I type in 'pip uninstall landlab' I get this message:  "Cannot uninstall requirement landlab, not installed".

I am using a 2013 MacBook Pro.

Thank you.

**Comment by kbarnhart** [comment]
@travisclow thanks for making this issue. 

Your conda installation is facing because landlab and its dependencies are in conflict with numba and its dependencies. I'm not super familiar with numba, so I won't speculate on the exact nature of this conflict. 

Do you know if numba was installed when you had your working install of landlab?

You have two main options for resolving this issue when you have this sort of issue:

1) use a conda environment for landlab. 
2) uninstall conflicting packages (and dependencies). 

I'd recommend option 1.

To create a conda environment you can do the following:
```
$ conda create --yes -n landlab python=2.7 # or 3.6
$ source activate landlab
$ conda install --yes landlab -c landlab
```

I would recommend that you read the documentation on conda environments  [here](https://conda.io/docs/user-guide/tasks/manage-environments.html). 

In order to use your conda environment, you'll have to activate the environment.

```
$ source activate landlab
```

let us know if this resolves your problems or if problems persist.

**Comment by kbarnhart** [comment]
@travisclow thanks for the update. I'm going to close the issue, but feel free to re-open it (or create a new issue) if need be.
