### ISSUE TITLE
stream_profiler broken by recent changes

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#690]
Hey @kbarnhart - just went to use the stream_profiler in some code from late last year, and discovered it's now nonfunctional. It would seem that you've fundamentally altered the way that some of the functions within the module are called; right now I'm tripping up on channel_nodes, but I haven't checked extensively what else might have changed.

Would appear that this is, essentially, no longer the same function that it was. i.e., the arguments supplied are now fundamentally different. I can change my own code, at the cost of a bit of time, but the wider issue here is that stuff like this will really piss off our users in the wild. It took me 15 mins to establish this was not a problem on my end, and I know what the architecture in github looks like...!

Can we roll this back? I appreciate that the new version works better, is more powerful, etc, but I was under the impression that *all* changes to non-underscored methods that have appeared in release versions should default to what they were before. A good option would seem to be to deprecate this function name, then bypass it with an alternative that does exactly what your new version does now. Would this work?

Sorry for not catching this sooner. I hadn't realised it had happened until right now. Good old friday afternoons, eh?

**Comment by kbarnhart** [comment]
@SiccarPoint I have no problem rolling this back.  Sorry for the headache its causing you. I'll try and make an hour to work on this today... Though ultimately I think that the new version is different enough that it it should be different (and implemented through the deprecation approach you propose). 

Can you send me a script that uses this tool in the way you want to use it?

This is because the underlying data structure now can handle multiple channels per watershed. This adds a layer to the lists of lists data structure. 

I think that the larger lesson from this issue is as follows: In revising this tool I faced the challenge that there were no tests outside of tutorials that used this function. This meant that if I had wanted to revise this in the right way I would have needed to first write a bunch of tests, then revise in such a way that I did not break the tests. I didn't have the bandwidth to make new tests, revise the code, etc. So I revised the code, and my tests for backwards compatibility were something like: do my best to run it in the way I had seen it previously used (in which I did not find problems). Then I wrote a bunch of new tests and documentation for the current version.

**Comment by SiccarPoint** [comment]
100% we need what you have now, it’s way cooler. And I think I’ve successfully modified my little workflow well enough now. I’m mostly worried about users out in the wild. 

Now I look, the way I had this set up before was pretty stupid (e.g., `channel_nodes` demanded the node steepnesses, then didn’t use them). Maybe we can smuggle these changes in without anyone noticing… Perhaps safer would be to just restore all the old code, deprecate the lot, put the current code back with differently named functions,  then just ensure all our current examples only use the new versions. This probably makes sense, since `channel_nodes` right now doesn’t return channel nodes, it returns a channel structure, and likewise get_distances_upstream. Might, e.g., get_channel_structure and get_channel_structure_distances work? Same for other tweaked stuff. This would be quite an ugly way of doing things, but maybe worth it? I’m sure @mcflugen will have an opinion on all this.

Better check there isn’t a broken old tutorial though. The basic components tutorial is the main one to check I think (there’s all sorts of bad practice still in there I think, esp. around flow routing!!)

**Comment by kbarnhart** [comment]
@mcflugen @SiccarPoint 

Another question ... We should probably test the tutorials repo agains landlab code base pull requests. 

Can we do this in an automated way (with the tutorials in a different repo)?


@SiccarPoint , I updated the components tutorial to use FlowAccumulator a bit ago (it might be in next, still, not sure)

**Comment by mcflugen** [comment]
@SiccarPoint @kbarnhart, I don't really know much about `stream_profiler` but I do have a couple general thoughts. Assuming the `channel_nodes` method is well named (that is, it describes what it does, fits our naming conventions, etc.), I don't think we should create a new method, that has a similar name, but that implements @kbarnhart's algorithm. This would result in two methods with essentially synonymous names. It wouldn't be obvious to users which one to use (e.g. `channel_nodes` vs. `get_channel_nodes`) and, by definition, one wouldn't fit our naming conventions.

However, if `channel_nodes` is not well named, I *might* be able to be convinced that the new-and-improved method could be renamed with a new-and-improved name and the old method marked as deprecated.

Another option would be to have some logic at the top of `channel_nodes` that tries to tell if a user is calling it as the old version or the new version and then executing the appropriate code (and issuing a deprecation warning if appropriate). I'm not sure if this would even be possible in this case, though.

**Comment by mcflugen** [comment]
@kbarnhart We could have the tutorials be tested every night. The `release` branch would use the latest landlab release and the `next` branch whatever's on master. That would be pretty simple.

We could also add some code that triggers a new build of the tutorials whenever the main landlab repository is updated. That would be a little more tricky. Definitely doable, though.
