### ISSUE TITLE
how do we test landlab locally?

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#700]
On this page of read the docs:
http://landlab.readthedocs.io/en/latest/dev_guide_install.html?highlight=test%20installed%20landlab#testing-the-landlab-installation

it states there are two ways to test Landlab:

`>>> import landlab`
`>>> landlab.test()`

OR

`$ python test-installed-landlab.py`

Neither of these seem to work now? Note from last call says "switch to pytest" but I realize now that I don't know what that means.

**Comment by kbarnhart** [comment]
`python scripts/test-installed-landlab.py` works for me. maybe that file got moved since the documentation was written. 

My understanding from the call was that switching to pytest has to do with using [pytest](http://pytest.orghttp://pytest.org) instead of [nose](http://nose.readthedocs.io/en/latest/) to run the actually tests --- and that @mcflugen is in the process of making that switch.

**Comment by mcflugen** [comment]
It works for me too. @nicgaspar, when you say "neither of these seem to work", what's the error that you're seeing?

**Comment by mcflugen** [comment]
@nicgaspar This is a problem with numpy 1.14. The issue was first reported in #616, which you can have a look at if you like, but the short answer is that this is a problem with numpy 1.14. The tests should run if you downgrade to 1.13. Note that landlab works with numpy 1.14 just fine, it's just that the tests don't run. This is one of the reasons we removed from our documentation the bit about how users should test their installation.

Since we've also discussed this error in  #625, #630, #632 maybe it's time to add something about it in the developer documentation?

**Comment by nicgaspar** [comment]
Yes, sorry for not noticing it in the issues. I obviously didn't check deeply enough. There is still reference in the documentation about testing, so it's not scrubbed everywhere. I can just add a note that tests will not work with numpy 1.14.
