### ISSUE TITLE
Format-related doctest failures in hex_lattice_tectonicizer

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#726]
Some of the doctest are failing as a result of format problems, such as:

Expected:
    array([0.8 , 1.26, 0.92, 0.79, 0.55, 1.04, 0.58, 2.22, 3.31, 0.48, 1.57])
Got:
    array([ 0.8 ,  1.26,  0.92,  0.79,  0.55,  1.04,  0.58,  2.22,  3.31,
            0.48,  1.57])

**Comment by mcflugen** [comment]
@gregtucker This is due to a difference with how numpy 1.14 prints arrays. Their release notes say that 1.14 includes *"Major improvements to printing of NumPy arrays and scalars".* I think the term, *"major improvements"* is debatable.

The easiest fix is to downgrade to *numpy<1.14* when running tests. A better solution is to add something like the following to `__init__.py`:
```python
try:
    np.set_printoptions(legacy='1.13')
except TypeError:
    pass
```
This may already have been done in an as-yet-unmerged branch. I'll have to check.
