### ISSUE TITLE
running pytest results in a figure being generated

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#756]
@mcflugen when I run `pytest` in the main directory, I get the following figure. 

<img width="752" alt="screen shot 2018-07-18 at 6 46 10 pm" src="https://user-images.githubusercontent.com/6589339/42920133-7b6b1fbc-8ad2-11e8-9bac-653822f1f6b2.png">

Does this happen to you?

**Comment by mcflugen** [comment]
@kbarnhart It does. It comes from the doctests in `landlab/ca/tests/grain_hill.py`. This is an example of *pytest* finding tests that *nose* missed. The figure can be suppressed by changing the doctests to set the `show_plots` keyword to `GrainHill` to *False*. So,
```python
>>> gh = GrainHill((3, 7), show_plots=False)
```
I guess we should fix this. I was going to leave it for a future pull request since it didn't cause the tests to break but maybe it's annoying enough to fix sooner rather than later.

**Comment by nicgaspar** [comment]
This doesn't happen for me. Maybe you already changed it? Should I close? @mcflugen

**Comment by kbarnhart** [comment]
@gregtucker says that this was a line of code never intended to be a unit test. So I'll assign him to fix this.

**Comment by kbarnhart** [comment]
This was addressed by PR #766. Closing
