### ISSUE TITLE
Intsalling landlab developer version on windows

### ISSUE THREAD

**Issue by jdgemperline** [landlab/landlab#773]
Hi, I'm having a similar issue that someone else appeared to have: https://github.com/landlab/landlab/issues/768

I'm getting the error, "Microsoft Visual C++ is required." when running python setup.py develope - the link specified in this error message is broken, but the link I followed in the closed issue above worked  (https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Visual_C.2B-.2B-_Build_Tools_2015_.28x86.2C_x64.2C_ARM.29). 

I downloaded Visual C++ version 14 as recommended since I have python 3.6.6, but I am still getting the same error message. I've only ever downloaded python 3, so I don't think I have the visual C++ for python 2.7 as listed in the issue above.

I'm also confused since the install directions for landlab say that Anaconda should come with it's own compiler. Thanks for any help!

**Comment by margauxmouchene** [comment]
Hi,
Sorry to hear you are having issues with the developer instal, and thank you for reporting your problem here.

With Python 3.6.6 you might have to install "[Microsoft Visual C++ 14.0 standalone: Build Tools for Visual Studio **2017**](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29)" (not 2015, as in the link you shared). Try uninstalling the 2015 version, upgrading setuptools (`conda update setuptools`) and installing the build tools for VS2017.

Yes you are right, Anaconda comes with compiler but depending on what else is installed on your computer, there might be conflicts between different versions of these tools.

Hope this helps, let us know if it works!

**Comment by jdgemperline** [comment]
I actually meant to include the link for the 2017 version, not the 2015 version on the same page. I checked and I do have the most up to date version. I tried updating setup tools again and then running the installation commands for landlab and I'm still getting the same error message, "Microsoft Visual C++ 14.0 is required"

**Comment by saisiddu** [comment]
Hi, I think Margaux listed all the things I tried (I am the author of the earlier *closed_issue* documenting my attempts to get this working). A quick question: are you installing everything as an 'administrator'? It may or may not affect this, but it is better to check.

**Comment by jdgemperline** [comment]
Thanks Margaux! I didn't realize that the C++ compiler was an 'optional' install for VS2017. There are several different 'workloads' or optional package downloads. I modified my install by checking the "Desktop Development for C++" option, then updated conda setuptools and installed and tested landlab successfully.

I didn't install all the individual C++ components since many of the options were related to Mac, Linux, and mobile C++ development. This seems to be working for my windows machine.

**Comment by jdgemperline** [comment]
Also just for reference, I ran the commands in Anaconda Prompt and that worked fine on the first try.

**Comment by margauxmouchene** [comment]
Awesome!
Thank you very much for the feedback, this might help other users.
