### ISSUE TITLE
field duplication in route-to-many FlowDirectors

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#774]
I think I've found a bug in the route-to-many FlowDirectors. By definition these produces arrays of outputs that are 2D, right? For FlowDirectorDINF at least, this gets saved in 'flow__receiver_node**s**'.

(I can see the naming logic of this, but I also don't like it, as it's inconsistent with the naming of the route-to-one routers, and since you can invoke a single FlowDirector or FlowAccumulator, I would say the fields produced by these should remain the same no matter what router you're using...)

That aside though, the actual problem is that somewhere along the line (during inheritance somewhere??), at least the FlowDirectorDINF is producing **both** 'flow__receiver_nodes' AND 'flow__receiver_node'. This is not right, surely; it should be one or the other. Haven't checked other route-to-many ones, but could be there too. Try:

```
>>> mg = RasterModelGrid((5, 5), dx=1.)
>>> mg.add_zeros('node', 'topographic__elevation', dtype=float)
>>> fd = FlowDirectorDINF(mg, 'topographic__elevation')
>>> fd.run_one_step()
>>> 'flow__receiver_node' in mg.at_node.keys()
True
>>> 'flow__receiver_nodes' in mg.at_node.keys()
True
```

This affects necessary type testing in components that only work with route-to-one routers.

**Comment by kbarnhart** [comment]
@SiccarPoint a quick response (again from the Munich airport).

This was intentional. Whether or not it is a bug, I'm not sure.

If you look at the docstrings [for MFD for example](https://landlab.readthedocs.io/en/latest/landlab.components.flow_director.html#landlab.components.flow_director.FlowDirectorMFD) you can see that the fields created are listed and include both fields. 

I did this because multiple flow direction algorithms need a (n-nodes, number of receivers) size array but expectation that 'flow__receiver_node' has a shape of (n-nodes,) for was very entrenched in other components (e.g. the lake mapper).

Looking briefly at other components that use the field `flow__receiver_node`, they may not work correctly with route-to-multiple components (e.g. I'm not sure if the stream power eroders only erode the steepest link or all active links). About to board the next flight so I'll check in about this later (at worst a week from today, after vacation and fieldwork).

**Comment by SiccarPoint** [comment]
That last observation was what motivated my issue: if components won't work right with a route-to-multiple flow direction schemes, then such routers should just not be producing a `flow__receiver_node` field at all. I can definitely be convinced that the two names are justified in different use cases, but 100% they should not be **both** produced by any given director. Route-to-multiples should give `flow__receiver_nodes` only, and route-to-one should give `flow__receiver_node` only.

(The alternative model would be to have them both use the `flow__receiver_node` field, but permit it to have different shapes. Would not be hard to find all the places in the components that currently use these fields, then enforce a shape test and raise an error as necessary.)

But this feels like a separate Issue. This one is simply that no FlowDirector should ever produce both fields, and at least one currently does.

**Comment by kbarnhart** [comment]
I just did some work on this on the plane. Will upload and respond when my
computer connects with WiFi next.

**Comment by kbarnhart** [comment]
@SiccarPoint I thought about this a bit and I think that route-to-multiple and route-to-one should use the same field names. I will admit that when I was developing this, I was pretty displeased with the solution I came up with. For some reason it felt better to make the field names different than to check the size and throw an error if a route-to-multiple was run along side something that doesn't work with it. 

As to a solution, I've started one and will make a PR. 

As best I can tell, three fields that matter here are: `flow__receiver_node`, `flow__link_to_reciever_node`, and `topographic__steepest_slope`. 

All of them are size (n-nodes, max-number-of-recievers).

I'll make some more notes about what has been done/what needs to be done for the PR. I'm unlikely to do much more on this in the next week (you caught me on a transit day), but I'll try and keep up with discussion in the meantime.
