### ISSUE TITLE
bug in as_id_array

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#843]
There's an issue with as_id_array. The function is followed (`core.utils` lns 182-197) by an unindented code block which is running as a meaningless script. I assume this is supposed to be inside the function?? Don't feel confident correcting this myself as I don't know the full intended functionality of the script - sorry to assign you Katy! (Also, it's untested?) Hopefully a very quick fix.

**Comment by kbarnhart** [comment]
@SiccarPoint I think @mcflugen is a more sensible assignee as he is the person git blame indicates made the original function.

**Comment by SiccarPoint** [comment]
Cool

**Comment by mcflugen** [comment]
@SiccarPoint Are you sure this is a bug? I *think* things are working correctly, however I could be wrong.

I think what you've found is simply old code that's not being used anymore. At one time I had intended to define `_as_id_array` functions (which would be called by `as_id_array`) that were specific to a platform (depending on the sizes of `np.int` and `np.intp`, which in most cases are the same). It turned out the code that's currently in `as_id_array` does the trick as is more compact so that's what I decided to go with. Apparently I didn't remove the old code.

Please let me know if things aren't behaving as you expect.

I'll create a pull request that removes the old code.

**Comment by SiccarPoint** [comment]
No, everything is behaving fine, I was just very disconcerted by the random code block! Thanks for checking and trimming.
