### ISSUE TITLE
Gully Head Cut

### ISSUE THREAD

**Issue by ogo15** [landlab/landlab#876]
Am  new to Landlab, am trying to model the gully head cut for a period of 20 years, please advise on the erosion model to be used and script examples if any. thanks

**Comment by gregtucker** [comment]
Landlab is a programming library rather than a model, though there are Components that provide numerical implementations for particular individual process laws. Suggest looking at the literature on gully erosion modeling to think about what kind of mathematics would be most suitable. For example, Kirkby and Bull (2000) Progress in Physical Geography; Istanbulluoglu et al. (2005) Journal of Geophysical Research; Flores-Cervantes et al. (2006) Journal of Geophysical Research; Rengers et al. (2014) Journal of Geophysical Research; papers by J. Poesen and colleagues, S. Bennett and colleagues.

**Comment by ogo15** [comment]
figured it out thanks
