### ISSUE TITLE
Subsetting a DataRecord doesn't return a true DataRecord

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#909]
Selecting a subset of a `DataRecord` (as shown by the MWE below) results in the
return of a `DataRecord` instance --- but one that does not have important attributes of DataRecord (for example the attribute `self._grid`). This means that it is not possible to run `self.calc_aggregate_value` which requires the grid to determine the size of the aggregate value array to create. 

This issue arose as @pfeiffea had asked me how to do a cleaner job indexing some
of the parcels stored in the in-progress NetworkSedimentTransporter (related to Issue #901 ).
I realized that part of the issue was that she really only wanted to deal with 
the current time step's parcels, so I tried to select just those and use them.

I then found this bug...

It would be great if indexing and selecting portions of the data record supported by Xarray (e.g. [these shown here](http://xarray.pydata.org/en/stable/indexing.html#indexing-and-selecting-data)) were supported by DataRecord. 

Tagging @nathanlyons and @margauxmouchene

```python

import numpy as np
from landlab.data_record import DataRecord
from landlab import RasterModelGrid
grid = RasterModelGrid((3,3))


element_id = np.array(
    [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 1], dtype=int
)
element_id = np.expand_dims(element_id, axis=1)
time = np.array([0.]) 

np.random.seed(0)

age = np.random.rand(np.size(element_id), np.size(time))  

items = {"grid_element": "node", "element_id": element_id}

variables = {"age": (["item_id", "time"], age)}

parcels = DataRecord(grid, items=items, time=time, data_vars=variables)

sel_time_parcels = parcels.sel(time=0)

sel_time_parcels
<xarray.DataRecord>
Dimensions:       (item_id: 15)
Coordinates:
    time          float64 0.0
  * item_id       (item_id) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
Data variables:
    grid_element  (item_id) object 'node' 'node' 'node' ... 'node' 'node' 'node'
    element_id    (item_id) int64 0 0 1 1 2 2 3 3 4 4 5 5 6 6 1
    age           (item_id) float64 0.5488 0.7152 0.6028 ... 0.9256 0.07104

s = sel_time_parcels.calc_aggregate_value(np.sum, data_variable='ages')

Traceback (most recent call last):

  File "<ipython-input-1-4a4df7dbc514>", line 33, in <module>
    s = sel_time_parcels.calc_aggregate_value(np.sum, data_variable='ages')

  File "/Users/barnhark/projects/landlab/allison/landlab/landlab/data_record/data_record.py", line 1034, in calc_aggregate_value
    out = np.nan * np.ones(self._grid[at].size)

  File "/anaconda3/lib/python3.7/site-packages/xarray/core/common.py", line 179, in __getattr__
    (type(self).__name__, name))

AttributeError: 'DataRecord' object has no attribute '_grid'
```

**Comment by kbarnhart** [comment]
@nathanlyons @margauxmouchene any thoughts on this. @pfeiffea and I are working on this and a fix would be great.

**Comment by nathanlyons** [comment]
@margauxmouchene Do you see a way to return a DataRecord from a method such as `sel` other than creating a `sel` method in DataRecord? If the latter, I wonder how many other xarray methods will require this that we have yet to discover.

In the light of this issue, #858, and other xarray methods that return a new Dataset: Is it instead worth it to make a Dataset a property of DataRecord instead of subclassing?

**Comment by kbarnhart** [comment]
@nathanlyons
I started on a fix that removes Dataset as a superclass (since we've discussed other reasons why this is a good idea...)

Will ping you when it is pushed.

**Comment by margauxmouchene** [comment]
Another solution is to use the filter in `calc_aggregate_value`:

`f = parcels['time'] == 0`
`s = parcels.calc_aggregate_value(np.sum, data_variable='ages', filter_array=f)`

**Comment by kbarnhart** [comment]
@pfeiffea and I have discussed this further, and decided that for now the real requirement she has is the permit dummy values (e.g. a value of link -999 for items that have moved off the grid). 

I've done this in #948 

There are 2 tests that I cannot figure out how to get to pass. If either @nathanlyons or @margauxmouchene has an idea of how to fix them it would be much appreciated. 

I write here a couple of things I've learned from working with DataRecord:

It has been really hard for me to figure out how to use it correctly. I feel like I have a good handle on using xarray... so this seems troubling. My issues dominantly focus on 
    a) Having a hard time making sure all the inputs are formatted correctly, specifically have the correct dimensions and
    b) Having a hard time improving the code when its been built to work with three coordinate options. 
    c) Have a hard time figure out the multiple layers of testing whether the element_id and grid_element values are correct. 

I don't really like our present approach of inheriting, and I also don't really like my approach of having a dataset as an attribute. It means that you need to know what methods are Dataset's and what methods are DataRecords. I don't have any good ideas here.

In working through this I started to think about what the smallest number of things that we might need to do to get an xarray dataset to BE a DataRecord. This is where I got:
1) We require that coordinates can only be in the following set ("item_id", "time")
2) We require two variables: "element_id" and "grid_element"
3) We require that these two variables only have certain set of valid values.

Other things (e.g. ffill method and calc_aggregate_value are wrappers on a chain of core xarray methods, that at the end of my current work, I don't know whether they are sensible...)

**Comment by nathanlyons** [comment]
I wonder if subclassing xr.Dataset will continues to be fraught with challenges especially given that xarray developers seem to warn against doing so. How about instead following xarray's suggestion by extending Dataset using an accessor? See http://xarray.pydata.org/en/stable/internals.html#extending-xarray

But overall I defer to @margauxmouchene who knows DataRecord better than I, and I understand that ClastTracker heavily relies on DataRecord. My suggestion above may be problematic for ClastTracker.

**Comment by margauxmouchene** [comment]
@kbarnhart: I agree with you that the current version of DataRecord is not straightforward to use, hence your issue a on input format. I am not sure I understand your issues b and c, but they are probably related. Input formats could be modified as to simplify things on the user's side and do all the required formatting under the hood. On the other hand, inheritance may also be a major problem so we need to rethink the whole component.

@nathanlyons: yes, let's try to find a better solution, since inheritance is not working and will always be problematic. However, I don't think accessors are the solution, here's why.

Ultimately, what we wanted to do in DataRecord was to have a record of variables relating to 1) the whole grid, and/or 2) things that live on the grid. What we want **is** a **Dataset** that has a **specific format**, the constraints on this format being:
- dimensions must be 'time' and/or 'item_id'
- if there are items, a  'grid_element' + 'element-id' combination must be provided for each item
- the 'grid_element' + 'element-id' combination must exist on the grid
We have also defined a few methods that are tailored to stick to the format but are pretty simple otherwise. The key element is the format.

So it makes sense (I think?) for DataRecord to be a _subclass_ of Dataset because it is a _certain type_ of Dataset. But I understand that inheritance is problematic. So what can we do?

My understanding of accessors is that they are meant to create extensions from xarray. The examples I've seen are all property-like extensions, the accessor implement a set of related functionalities under a single package name (to avoid conflicts with native xarray method names, among other things). In particular, accessors should only accept one argument, which is an xarray.Dataset (an exmple [here](https://github.com/pydata/xarray/issues/2473)). This doesn't seem to be the right tool to constrain the data structure itself.

I am not totally sure what's the best solution. I am testing a version where I use the `__new__` method to force `__init__` to return a Dataset directly. That is:

`from landlab import DataRecord`
`dr = DataRecord(grid, time = ....)`
`dr`

would give:
`<xarray.Dataset>`
`Dimensions: ...`
`Coordinates: ...`
`Data variables: ...`
`Attributes: ...`

(as opposed to needing to call `dr.dataset` in Katy's version). 
So you would be able to call directly both Dataset native methods and DataRecord methods from:
`dr.method()`

What do you guys think?

I'll keep you updated on my progress.

**Comment by kbarnhart** [comment]
@margauxmouchene I agree with you that the accessors don't seem to be quite right. 

My impression of what we want is:
1) An xarray Dataset in which we can enforce a small number of constraints related to a Landlab grid (which means that it needs to be passed). (I think I listed them above).
2) The ability to extend the Dataset to include functions (as @margauxmouchene pointed out)

My impression is that if the xarray developers advocate against subclassing Dataset, then we should move DataRecord away from that implementation. I think the approach you are describing with `__new__` still keeps DataRecord as a subclass, yes?

**Comment by margauxmouchene** [comment]
@kbarnhart I was thinking about something similar to what you had previously done with `ItemCollection`.  
`DataRecord` would be something like:

`from xarray import Dataset`
`class DataRecord(object):`

`def __new__(cls, grid=..., time=..., etc.):`
`ds=Dataset(...)`   (to build the Dataset from user input data)
`return ds`

`def __init__(self, ...):`
`...`

So that the created object **is** directly a Dataset (as opposed to ItemCollection where we had to call `itemcollection.Dataframe` to access the dataframe).

So far I was able to create the dataset but I'm not sure how to implement functions that we can call from `dr.method()` (with `dr` being an instance of DaataRecord)
