### ISSUE TITLE
requirements.txt for a developer

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#911]
We don't enforce enough requirements.txt for a developer install. Both `pytest-cov` and (apparently; see #910) `pyqt` are essential to run the tests locally, so should be in the file. Could consider a separate file for developers, but don't really see why we wouldn't just do this for everybody.

I note the `pyqt` thing is tricksy, as it raises cryptic c++ library errors. This makes it doubly important.

**Comment by kbarnhart** [comment]
I month or so ago I was discussing a related topic with @mcflugen. Namely, that requirements are listed in multiple places (the requirements.txt file, the conda recipe, etc). 

I got the impression from @mcflugen that it was more appropriate to just put the dependencies for _running_ rather than _building_ and _running_ and _testing_ in the requirements.txt file (please correct me if I misremember)... 

Another type of package to consider is something like `flake8`... it is functionally necessary to test if the code is lint-compatible...

`isort` and `black` are necessary if you want to take advantage of `make pretty`... 

The conda recipe (meta.yaml) breaks some of these categories out (which I find helpful). 

I think it would be great if we could simultaneously:
a) clean up/add to the requirements.txt file
b) remove unnecessary bits of recipes we are not really using anymore (due to conda forge)
c) be clear about what is needed to build/run/test...

**Comment by kbarnhart** [comment]
as @mcflugen addressed this in #915 I'm closing this. 

I also updated some of the information on Updating and Installing (dev version) on the wiki indicating what to do if setup.py or requirements-dev change.
