### ISSUE TITLE
Best method for id'ing nodes on grids/DEMs?

### ISSUE THREAD

**Issue by jmdelvecchio** [landlab/landlab#973]
I've pored over tutorials and comments and can't find a fix, so I'll ask here in case others have the issue (and it's not just me being new). 

How can I determine the node ID(s) for a point or region of interest on my grid in order to query their properties as I step through time, etc? For example: I'm attempting to track 1D elevation changes with time in hollows in a grid (a read-in ascii DEM) with 10^6 nodes. (Useful? image attached). I can plot the whole-grid difference between timesteps, but I want to track changes at points as a line plot. I tried to do the math to determine the node ID of a point in the hollow given the pixel's x and y coordinates (count how many nodes wide the grid is, then count how many nodes up and across the pixel was) but I didn't get the answer I expected since my raster resolution wasn't an integer, and I assume this wouldn't work with an odd grid shape, _and_ it gave me a headache.  

I also see how to plot topographic profiles in the "plotting" tutorial, but I haven't gotten reshaping etc. to help, though I suspect that's the route to take. 

Any guidance is appreciated! 

(running on Windows, 1.9.0) 
![landlab1](https://user-images.githubusercontent.com/17852785/61386820-30cd2680-a872-11e9-8bb1-1d7e2576342f.PNG)

**Comment by SiccarPoint** [comment]
Try the `find_nearest_node` method of the grid. This definitely exists for rasters, and I believe it does for Voronois as well. You still have to read it off the plot by hand, but it should do the job once you know (x, y).

See:
https://landlab.readthedocs.io/en/latest/landlab.grid.html#landlab.grid.raster.RasterModelGrid.find_nearest_node

**Comment by jmdelvecchio** [comment]
Yes, thank you, exactly the function I needed, hiding somewhere! (hashtag rtfm)

If you have time to settle a less-urgent, related question: the coordinates that find_nearest_node takes are read from the ascii file so they're something nasty like ([1212210, -708749]); as I read the imshow and ModelGrid docs I can't find an easy way to specify that the plot take the ascii file's x and y coordinates instead of starting at 0,0 (once I reshape and plot 2-d profiles it reads the ascii coordinates). I just added the y and x corner coordinates from the ascii file to the Landlab coordinates to solve my problem. 

thanks again!!

**Comment by SiccarPoint** [comment]
Our functions like to hide - we need a way of indexing them better still!

Re absolute coordinates vs relative to (0, 0), this is something @kbarnhart has been thinking about, and hopefully she can chime in.

**Comment by gregtucker** [comment]
JoanMarie, there is also the Landlab Grid Sketchbook (which we haven't formally released because we're waiting for a couple of minor upgrades). It's a web-based graphical tool that displays grid elements and their ID numbers. However, I just checked and the server doesn't seem to be working. @mcflugen or @jennyknuth any idea why https://landlab.github.io/grid-sketchbook/ displays a blank screen?

**Comment by nicgaspar** [comment]
@jmdelvecchio Are you only working in Jupyter Notebooks? If you plot (at least) a raster grid using Anaconda Spyder, but not inline, i.e. the plot pops out in a separate window, you can actually query the grid by just clicking on it. @nathanlyons wrote that functionality, but I don't think it works in a Jupyter Notebook.

**Comment by kbarnhart** [comment]
@jmdelvecchio  

If your DEM has header values for `xllcorner` and `yllcorner`, the function `read_esrii_ascii` should pay attention to your DEM coordinates and sets the lower left corner of the grid to the correct value. Thus your `grid.x_of_node` and `grid.y_of_node` reflect the UTM coordinates, and when you use the `find_nearest_node` function recommended by @SiccarPoint you should end up with a node id that is correct. 

You can test this by printing out `grid.x_of_node` or `grid.y_of_node`. You should get values that look like your UTM coordinates. If for some reason your ascii file doesn't include the `xllcorner` and `yllcorner` information, you should see values that start from 0. 

If all you want to do is grab the information from that node through time, you shouldn't need to worry about the coordinate translation for plotting. 

If, however, you want to plot that x,y coordinate on the result of imshow_grid, you will run into a problem (as you described). `imshow_grid` presently plots using x and y coordinates relative to (0,0). I was the person who added the functionality to `read_esri_ascii` to pay attention to the lower left coordinate. @mcflugen and I discussed this inconsistency with `imshow_grid` and decided to leave it because printing UTM coordinates can get really ugly (if you think this should change, please submit an issue requesting it). 

The best workaround that I know of is to do what you described and translate the known x-y point by the lower left corner of the grid. 

You can access it using `grid.xy_of_lower_left` or with `grid.x_of_node[0]` and `grid.y_of_node[0]`

So if `ind` where your index of a hollow, and you want to plot a red dot over the hollow you might write:
```python
plt.imshow(mg, "topographic__elevation")
plt.plot(
    grid.x_of_node[ind]-grid.xy_of_lower_left[0], 
    grid.y_of_node[ind]-grid.xy_of_lower_left[1], 
    'r.')

Let me know if you have other questions.

**Comment by jmdelvecchio** [comment]
All great suggestions everyone, thanks! The dot idea is good @kbarnhart and @nicgaspar I have been using notebooks but now I know Spyder would be useful for that!

**Comment by kbarnhart** [comment]
@jmdelvecchio did you get all the answers you needed? If so, OK to close this issue?
